# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BeyoncePage.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BeyoncePage(object):
    def setupUi(self, BeyoncePage):
        BeyoncePage.setObjectName("BeyoncePage")
        BeyoncePage.resize(1920, 1080)
        BeyoncePage.setMinimumSize(QtCore.QSize(1920, 1080))
        BeyoncePage.setMaximumSize(QtCore.QSize(1920, 1080))
        self.centralwidget = QtWidgets.QWidget(BeyoncePage)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, -50, 1920, 1080))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(1920, 1080))
        self.label.setMaximumSize(QtCore.QSize(1920, 1080))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("BeyoncePage.png"))
        self.label.setObjectName("label")
        self.BeyonceBackBtn = QtWidgets.QPushButton(self.centralwidget)
        self.BeyonceBackBtn.setGeometry(QtCore.QRect(1750, 940, 151, 71))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.BeyonceBackBtn.setFont(font)
        self.BeyonceBackBtn.setStyleSheet("\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"\n"
"")
        self.BeyonceBackBtn.setObjectName("BeyonceBackBtn")
        self.DateBeyonceComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.DateBeyonceComboBox.setGeometry(QtCore.QRect(330, 560, 191, 41))
        self.DateBeyonceComboBox.setStyleSheet("\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"\n"
"")
        self.DateBeyonceComboBox.setObjectName("DateBeyonceComboBox")
        self.DateBeyonceComboBox.addItem("")
        self.DateBeyonceComboBox.addItem("")
        self.DateBeyonceComboBox.addItem("")
        self.DateBeyonceComboBox.addItem("")
        self.DateBeyonceComboBox.addItem("")
        self.DateBeyonceComboBox.addItem("")
        self.DateBeyonceComboBox.addItem("")
        self.BeyoncePriceLabel = QtWidgets.QLabel(self.centralwidget)
        self.BeyoncePriceLabel.setGeometry(QtCore.QRect(70, 490, 451, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.BeyoncePriceLabel.setFont(font)
        self.BeyoncePriceLabel.setStyleSheet("QLabel {\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.BeyoncePriceLabel.setObjectName("BeyoncePriceLabel")
        self.DateBeyonceLabel = QtWidgets.QLabel(self.centralwidget)
        self.DateBeyonceLabel.setGeometry(QtCore.QRect(70, 560, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.DateBeyonceLabel.setFont(font)
        self.DateBeyonceLabel.setStyleSheet("QLabel {\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.DateBeyonceLabel.setObjectName("DateBeyonceLabel")
        self.QuantityBeyonceLabel = QtWidgets.QLabel(self.centralwidget)
        self.QuantityBeyonceLabel.setGeometry(QtCore.QRect(70, 620, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.QuantityBeyonceLabel.setFont(font)
        self.QuantityBeyonceLabel.setStyleSheet("QLabel {\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.QuantityBeyonceLabel.setObjectName("QuantityBeyonceLabel")
        self.ConfirmBeyonceBtn = QtWidgets.QPushButton(self.centralwidget)
        self.ConfirmBeyonceBtn.setGeometry(QtCore.QRect(250, 850, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ConfirmBeyonceBtn.setFont(font)
        self.ConfirmBeyonceBtn.setStyleSheet("\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"\n"
"")
        self.ConfirmBeyonceBtn.setObjectName("ConfirmBeyonceBtn")
        self.RowBeyonceLabel = QtWidgets.QLabel(self.centralwidget)
        self.RowBeyonceLabel.setGeometry(QtCore.QRect(70, 680, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.RowBeyonceLabel.setFont(font)
        self.RowBeyonceLabel.setStyleSheet("QLabel {\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.RowBeyonceLabel.setObjectName("RowBeyonceLabel")
        self.SeatBeyonceLabel = QtWidgets.QLabel(self.centralwidget)
        self.SeatBeyonceLabel.setGeometry(QtCore.QRect(70, 740, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.SeatBeyonceLabel.setFont(font)
        self.SeatBeyonceLabel.setStyleSheet("QLabel {\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.SeatBeyonceLabel.setObjectName("SeatBeyonceLabel")
        self.RowBeyonceComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.RowBeyonceComboBox.setGeometry(QtCore.QRect(330, 680, 191, 41))
        self.RowBeyonceComboBox.setStyleSheet("\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"\n"
"")
        self.RowBeyonceComboBox.setObjectName("RowBeyonceComboBox")
        self.RowBeyonceComboBox.addItem("")
        self.RowBeyonceComboBox.addItem("")
        self.RowBeyonceComboBox.addItem("")
        self.RowBeyonceComboBox.addItem("")
        self.RowBeyonceComboBox.addItem("")
        self.RowBeyonceComboBox.addItem("")
        self.RowBeyonceComboBox.addItem("")
        self.RowBeyonceComboBox.addItem("")
        self.RowBeyonceComboBox.addItem("")
        self.RowBeyonceComboBox.addItem("")
        self.RowBeyonceComboBox.addItem("")
        self.RowBeyonceComboBox.addItem("")
        self.RowBeyonceComboBox.addItem("")
        self.RowBeyonceComboBox.addItem("")
        self.RowBeyonceComboBox.addItem("")
        self.RowBeyonceComboBox.addItem("")
        self.RowBeyonceComboBox.addItem("")
        self.RowBeyonceComboBox.addItem("")
        self.RowBeyonceComboBox.addItem("")
        self.RowBeyonceComboBox.addItem("")
        self.RowBeyonceComboBox.addItem("")
        self.RowBeyonceComboBox.addItem("")
        self.RowBeyonceComboBox.addItem("")
        self.RowBeyonceComboBox.addItem("")
        self.RowBeyonceComboBox.addItem("")
        self.RowBeyonceComboBox.addItem("")
        self.RowBeyonceComboBox.addItem("")
        self.RowBeyonceComboBox.addItem("")
        self.RowBeyonceComboBox.addItem("")
        self.RowBeyonceComboBox.addItem("")
        self.SeatBeyonceComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.SeatBeyonceComboBox.setGeometry(QtCore.QRect(330, 740, 191, 41))
        self.SeatBeyonceComboBox.setStyleSheet("\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"\n"
"")
        self.SeatBeyonceComboBox.setObjectName("SeatBeyonceComboBox")
        self.SeatBeyonceComboBox.addItem("")
        self.SeatBeyonceComboBox.addItem("")
        self.SeatBeyonceComboBox.addItem("")
        self.SeatBeyonceComboBox.addItem("")
        self.SeatBeyonceComboBox.addItem("")
        self.SeatBeyonceComboBox.addItem("")
        self.SeatBeyonceComboBox.addItem("")
        self.SeatBeyonceComboBox.addItem("")
        self.SeatBeyonceComboBox.addItem("")
        self.SeatBeyonceComboBox.addItem("")
        self.SeatBeyonceComboBox.addItem("")
        self.SeatBeyonceComboBox.addItem("")
        self.SeatBeyonceComboBox.addItem("")
        self.SeatBeyonceComboBox.addItem("")
        self.SeatBeyonceComboBox.addItem("")
        self.SeatBeyonceComboBox.addItem("")
        self.SeatBeyonceComboBox.addItem("")
        self.SeatBeyonceComboBox.addItem("")
        self.SeatBeyonceComboBox.addItem("")
        self.SeatBeyonceComboBox.addItem("")
        self.SeatBeyonceComboBox.addItem("")
        self.SeatBeyonceComboBox.addItem("")
        self.SeatBeyonceComboBox.addItem("")
        self.SeatBeyonceComboBox.addItem("")
        self.SeatBeyonceComboBox.addItem("")
        self.SeatBeyonceComboBox.addItem("")
        self.SeatBeyonceComboBox.addItem("")
        self.SeatBeyonceComboBox.addItem("")
        self.SeatBeyonceComboBox.addItem("")
        self.SeatBeyonceComboBox.addItem("")
        self.TotalBeyonceLabel = QtWidgets.QLabel(self.centralwidget)
        self.TotalBeyonceLabel.setGeometry(QtCore.QRect(70, 800, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.TotalBeyonceLabel.setFont(font)
        self.TotalBeyonceLabel.setStyleSheet("QLabel {\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.TotalBeyonceLabel.setObjectName("TotalBeyonceLabel")
        self.TotalBeyonceLabelValue = QtWidgets.QLabel(self.centralwidget)
        self.TotalBeyonceLabelValue.setGeometry(QtCore.QRect(330, 800, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.TotalBeyonceLabelValue.setFont(font)
        self.TotalBeyonceLabelValue.setStyleSheet("QLabel {\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.TotalBeyonceLabelValue.setObjectName("TotalBeyonceLabelValue")
        self.PayBeyonceBtn = QtWidgets.QPushButton(self.centralwidget)
        self.PayBeyonceBtn.setEnabled(False)
        self.PayBeyonceBtn.setGeometry(QtCore.QRect(430, 930, 271, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.PayBeyonceBtn.setFont(font)
        self.PayBeyonceBtn.setStyleSheet("\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"\n"
"")
        self.PayBeyonceBtn.setObjectName("PayBeyonceBtn")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(330, 620, 191, 41))
        self.lineEdit.setStyleSheet("\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"")
        self.lineEdit.setObjectName("lineEdit")
        BeyoncePage.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(BeyoncePage)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1920, 26))
        self.menubar.setObjectName("menubar")
        BeyoncePage.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(BeyoncePage)
        self.statusbar.setObjectName("statusbar")
        BeyoncePage.setStatusBar(self.statusbar)

        self.retranslateUi(BeyoncePage)
        QtCore.QMetaObject.connectSlotsByName(BeyoncePage)

    def retranslateUi(self, BeyoncePage):
        _translate = QtCore.QCoreApplication.translate
        BeyoncePage.setWindowTitle(_translate("BeyoncePage", "MainWindow"))
        self.BeyonceBackBtn.setText(_translate("BeyoncePage", "<"))
        self.DateBeyonceComboBox.setItemText(0, _translate("BeyoncePage", "4 July - Washington, D.C. (Landover) @ Northwest Stadium"))
        self.DateBeyonceComboBox.setItemText(1, _translate("BeyoncePage", "7 July - Washington, D.C. (Landover) @ Northwest Stadium"))
        self.DateBeyonceComboBox.setItemText(2, _translate("BeyoncePage", "10 July -Atlanta, GA @ Mercedes-Benz Stadium"))
        self.DateBeyonceComboBox.setItemText(3, _translate("BeyoncePage", "11 July -Atlanta, GA @ Mercedes-Benz Stadium"))
        self.DateBeyonceComboBox.setItemText(4, _translate("BeyoncePage", "13 July -Atlanta, GA @ Mercedes-Benz Stadium"))
        self.DateBeyonceComboBox.setItemText(5, _translate("BeyoncePage", "14 July -Atlanta, GA @ Mercedes-Benz Stadium"))
        self.DateBeyonceComboBox.setItemText(6, _translate("BeyoncePage", "25 July -Las Vegas, NV @ Allegiant Stadium "))
        self.BeyoncePriceLabel.setText(_translate("BeyoncePage", "Price : 300$"))
        self.DateBeyonceLabel.setText(_translate("BeyoncePage", "Date & City"))
        self.QuantityBeyonceLabel.setText(_translate("BeyoncePage", "Quantity"))
        self.ConfirmBeyonceBtn.setText(_translate("BeyoncePage", "Confirm "))
        self.RowBeyonceLabel.setText(_translate("BeyoncePage", "The Row"))
        self.SeatBeyonceLabel.setText(_translate("BeyoncePage", "The seat"))
        self.RowBeyonceComboBox.setItemText(0, _translate("BeyoncePage", "1"))
        self.RowBeyonceComboBox.setItemText(1, _translate("BeyoncePage", "2"))
        self.RowBeyonceComboBox.setItemText(2, _translate("BeyoncePage", "3"))
        self.RowBeyonceComboBox.setItemText(3, _translate("BeyoncePage", "4"))
        self.RowBeyonceComboBox.setItemText(4, _translate("BeyoncePage", "5"))
        self.RowBeyonceComboBox.setItemText(5, _translate("BeyoncePage", "6"))
        self.RowBeyonceComboBox.setItemText(6, _translate("BeyoncePage", "7"))
        self.RowBeyonceComboBox.setItemText(7, _translate("BeyoncePage", "8"))
        self.RowBeyonceComboBox.setItemText(8, _translate("BeyoncePage", "9"))
        self.RowBeyonceComboBox.setItemText(9, _translate("BeyoncePage", "10"))
        self.RowBeyonceComboBox.setItemText(10, _translate("BeyoncePage", "11"))
        self.RowBeyonceComboBox.setItemText(11, _translate("BeyoncePage", "12"))
        self.RowBeyonceComboBox.setItemText(12, _translate("BeyoncePage", "13"))
        self.RowBeyonceComboBox.setItemText(13, _translate("BeyoncePage", "14"))
        self.RowBeyonceComboBox.setItemText(14, _translate("BeyoncePage", "15"))
        self.RowBeyonceComboBox.setItemText(15, _translate("BeyoncePage", "16"))
        self.RowBeyonceComboBox.setItemText(16, _translate("BeyoncePage", "17"))
        self.RowBeyonceComboBox.setItemText(17, _translate("BeyoncePage", "18"))
        self.RowBeyonceComboBox.setItemText(18, _translate("BeyoncePage", "19"))
        self.RowBeyonceComboBox.setItemText(19, _translate("BeyoncePage", "20"))
        self.RowBeyonceComboBox.setItemText(20, _translate("BeyoncePage", "21"))
        self.RowBeyonceComboBox.setItemText(21, _translate("BeyoncePage", "22"))
        self.RowBeyonceComboBox.setItemText(22, _translate("BeyoncePage", "23"))
        self.RowBeyonceComboBox.setItemText(23, _translate("BeyoncePage", "24"))
        self.RowBeyonceComboBox.setItemText(24, _translate("BeyoncePage", "25"))
        self.RowBeyonceComboBox.setItemText(25, _translate("BeyoncePage", "26"))
        self.RowBeyonceComboBox.setItemText(26, _translate("BeyoncePage", "27"))
        self.RowBeyonceComboBox.setItemText(27, _translate("BeyoncePage", "28"))
        self.RowBeyonceComboBox.setItemText(28, _translate("BeyoncePage", "29"))
        self.RowBeyonceComboBox.setItemText(29, _translate("BeyoncePage", "30"))
        self.SeatBeyonceComboBox.setItemText(0, _translate("BeyoncePage", "1"))
        self.SeatBeyonceComboBox.setItemText(1, _translate("BeyoncePage", "2"))
        self.SeatBeyonceComboBox.setItemText(2, _translate("BeyoncePage", "3"))
        self.SeatBeyonceComboBox.setItemText(3, _translate("BeyoncePage", "4"))
        self.SeatBeyonceComboBox.setItemText(4, _translate("BeyoncePage", "5"))
        self.SeatBeyonceComboBox.setItemText(5, _translate("BeyoncePage", "6"))
        self.SeatBeyonceComboBox.setItemText(6, _translate("BeyoncePage", "7"))
        self.SeatBeyonceComboBox.setItemText(7, _translate("BeyoncePage", "8"))
        self.SeatBeyonceComboBox.setItemText(8, _translate("BeyoncePage", "9"))
        self.SeatBeyonceComboBox.setItemText(9, _translate("BeyoncePage", "10"))
        self.SeatBeyonceComboBox.setItemText(10, _translate("BeyoncePage", "11"))
        self.SeatBeyonceComboBox.setItemText(11, _translate("BeyoncePage", "12"))
        self.SeatBeyonceComboBox.setItemText(12, _translate("BeyoncePage", "13"))
        self.SeatBeyonceComboBox.setItemText(13, _translate("BeyoncePage", "14"))
        self.SeatBeyonceComboBox.setItemText(14, _translate("BeyoncePage", "15"))
        self.SeatBeyonceComboBox.setItemText(15, _translate("BeyoncePage", "16"))
        self.SeatBeyonceComboBox.setItemText(16, _translate("BeyoncePage", "17"))
        self.SeatBeyonceComboBox.setItemText(17, _translate("BeyoncePage", "18"))
        self.SeatBeyonceComboBox.setItemText(18, _translate("BeyoncePage", "19"))
        self.SeatBeyonceComboBox.setItemText(19, _translate("BeyoncePage", "20"))
        self.SeatBeyonceComboBox.setItemText(20, _translate("BeyoncePage", "21"))
        self.SeatBeyonceComboBox.setItemText(21, _translate("BeyoncePage", "22"))
        self.SeatBeyonceComboBox.setItemText(22, _translate("BeyoncePage", "23"))
        self.SeatBeyonceComboBox.setItemText(23, _translate("BeyoncePage", "24"))
        self.SeatBeyonceComboBox.setItemText(24, _translate("BeyoncePage", "25"))
        self.SeatBeyonceComboBox.setItemText(25, _translate("BeyoncePage", "26"))
        self.SeatBeyonceComboBox.setItemText(26, _translate("BeyoncePage", "27"))
        self.SeatBeyonceComboBox.setItemText(27, _translate("BeyoncePage", "28"))
        self.SeatBeyonceComboBox.setItemText(28, _translate("BeyoncePage", "29"))
        self.SeatBeyonceComboBox.setItemText(29, _translate("BeyoncePage", "30"))
        self.TotalBeyonceLabel.setText(_translate("BeyoncePage", "In Total"))
        self.TotalBeyonceLabelValue.setText(_translate("BeyoncePage", "0$"))
        self.PayBeyonceBtn.setText(_translate("BeyoncePage", "Choose The Quantity First"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    BeyoncePage = QtWidgets.QMainWindow()
    ui = Ui_BeyoncePage()
    ui.setupUi(BeyoncePage)
    BeyoncePage.show()
    sys.exit(app.exec_())
