# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BilliePage.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BilleiPage(object):
    def setupUi(self, BilleiPage):
        BilleiPage.setObjectName("BilleiPage")
        BilleiPage.resize(1920, 1080)
        BilleiPage.setMinimumSize(QtCore.QSize(1920, 1080))
        BilleiPage.setMaximumSize(QtCore.QSize(1920, 1080))
        self.centralwidget = QtWidgets.QWidget(BilleiPage)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, -50, 1920, 1080))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(1920, 1080))
        self.label.setMaximumSize(QtCore.QSize(1920, 1080))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("BilliePage.png"))
        self.label.setObjectName("label")
        self.BillieBackBtn = QtWidgets.QPushButton(self.centralwidget)
        self.BillieBackBtn.setGeometry(QtCore.QRect(1750, 940, 151, 71))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.BillieBackBtn.setFont(font)
        self.BillieBackBtn.setStyleSheet("\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"\n"
"")
        self.BillieBackBtn.setObjectName("BillieBackBtn")
        self.DateBillieComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.DateBillieComboBox.setGeometry(QtCore.QRect(330, 560, 191, 41))
        self.DateBillieComboBox.setStyleSheet("\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"\n"
"")
        self.DateBillieComboBox.setObjectName("DateBillieComboBox")
        self.DateBillieComboBox.addItem("")
        self.DateBillieComboBox.addItem("")
        self.DateBillieComboBox.addItem("")
        self.DateBillieComboBox.addItem("")
        self.DateBillieComboBox.addItem("")
        self.DateBillieComboBox.addItem("")
        self.DateBillieComboBox.addItem("")
        self.DateBillieComboBox.addItem("")
        self.DateBillieComboBox.addItem("")
        self.DateBillieComboBox.addItem("")
        self.DateBillieComboBox.addItem("")
        self.DateBillieComboBox.addItem("")
        self.DateBillieComboBox.addItem("")
        self.DateBillieComboBox.addItem("")
        self.DateBillieComboBox.addItem("")
        self.DateBillieComboBox.addItem("")
        self.DateBillieComboBox.addItem("")
        self.DateBillieComboBox.addItem("")
        self.DateBillieComboBox.addItem("")
        self.DateBillieComboBox.addItem("")
        self.DateBillieComboBox.addItem("")
        self.DateBillieComboBox.addItem("")
        self.DateBillieComboBox.addItem("")
        self.DateBillieComboBox.addItem("")
        self.DateBillieComboBox.addItem("")
        self.DateBillieComboBox.addItem("")
        self.DateBillieComboBox.addItem("")
        self.DateBillieComboBox.addItem("")
        self.DateBillieComboBox.addItem("")
        self.DateBillieComboBox.addItem("")
        self.DateBillieComboBox.addItem("")
        self.DateBillieComboBox.addItem("")
        self.DateBillieComboBox.addItem("")
        self.DateBillieComboBox.addItem("")
        self.DateBillieComboBox.addItem("")
        self.DateBillieComboBox.addItem("")
        self.BilliePriceLabel = QtWidgets.QLabel(self.centralwidget)
        self.BilliePriceLabel.setGeometry(QtCore.QRect(70, 490, 451, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.BilliePriceLabel.setFont(font)
        self.BilliePriceLabel.setStyleSheet("QLabel {\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.BilliePriceLabel.setObjectName("BilliePriceLabel")
        self.DateBillieLabel = QtWidgets.QLabel(self.centralwidget)
        self.DateBillieLabel.setGeometry(QtCore.QRect(70, 560, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.DateBillieLabel.setFont(font)
        self.DateBillieLabel.setStyleSheet("QLabel {\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.DateBillieLabel.setObjectName("DateBillieLabel")
        self.QuantityBillieLabel = QtWidgets.QLabel(self.centralwidget)
        self.QuantityBillieLabel.setGeometry(QtCore.QRect(70, 620, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.QuantityBillieLabel.setFont(font)
        self.QuantityBillieLabel.setStyleSheet("QLabel {\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.QuantityBillieLabel.setObjectName("QuantityBillieLabel")
        self.ConfirmBillieBtn = QtWidgets.QPushButton(self.centralwidget)
        self.ConfirmBillieBtn.setGeometry(QtCore.QRect(250, 850, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ConfirmBillieBtn.setFont(font)
        self.ConfirmBillieBtn.setStyleSheet("\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"\n"
"")
        self.ConfirmBillieBtn.setObjectName("ConfirmBillieBtn")
        self.RowBillieLabel = QtWidgets.QLabel(self.centralwidget)
        self.RowBillieLabel.setGeometry(QtCore.QRect(70, 680, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.RowBillieLabel.setFont(font)
        self.RowBillieLabel.setStyleSheet("QLabel {\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.RowBillieLabel.setObjectName("RowBillieLabel")
        self.SeatBilieLabel = QtWidgets.QLabel(self.centralwidget)
        self.SeatBilieLabel.setGeometry(QtCore.QRect(70, 740, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.SeatBilieLabel.setFont(font)
        self.SeatBilieLabel.setStyleSheet("QLabel {\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.SeatBilieLabel.setObjectName("SeatBilieLabel")
        self.RowBillieComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.RowBillieComboBox.setGeometry(QtCore.QRect(330, 680, 191, 41))
        self.RowBillieComboBox.setStyleSheet("\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"\n"
"")
        self.RowBillieComboBox.setObjectName("RowBillieComboBox")
        self.RowBillieComboBox.addItem("")
        self.RowBillieComboBox.addItem("")
        self.RowBillieComboBox.addItem("")
        self.RowBillieComboBox.addItem("")
        self.RowBillieComboBox.addItem("")
        self.RowBillieComboBox.addItem("")
        self.RowBillieComboBox.addItem("")
        self.RowBillieComboBox.addItem("")
        self.RowBillieComboBox.addItem("")
        self.RowBillieComboBox.addItem("")
        self.RowBillieComboBox.addItem("")
        self.RowBillieComboBox.addItem("")
        self.RowBillieComboBox.addItem("")
        self.RowBillieComboBox.addItem("")
        self.RowBillieComboBox.addItem("")
        self.RowBillieComboBox.addItem("")
        self.RowBillieComboBox.addItem("")
        self.RowBillieComboBox.addItem("")
        self.RowBillieComboBox.addItem("")
        self.RowBillieComboBox.addItem("")
        self.RowBillieComboBox.addItem("")
        self.RowBillieComboBox.addItem("")
        self.RowBillieComboBox.addItem("")
        self.RowBillieComboBox.addItem("")
        self.RowBillieComboBox.addItem("")
        self.RowBillieComboBox.addItem("")
        self.RowBillieComboBox.addItem("")
        self.RowBillieComboBox.addItem("")
        self.RowBillieComboBox.addItem("")
        self.RowBillieComboBox.addItem("")
        self.SeatBillieComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.SeatBillieComboBox.setGeometry(QtCore.QRect(330, 740, 191, 41))
        self.SeatBillieComboBox.setStyleSheet("\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"\n"
"")
        self.SeatBillieComboBox.setObjectName("SeatBillieComboBox")
        self.SeatBillieComboBox.addItem("")
        self.SeatBillieComboBox.addItem("")
        self.SeatBillieComboBox.addItem("")
        self.SeatBillieComboBox.addItem("")
        self.SeatBillieComboBox.addItem("")
        self.SeatBillieComboBox.addItem("")
        self.SeatBillieComboBox.addItem("")
        self.SeatBillieComboBox.addItem("")
        self.SeatBillieComboBox.addItem("")
        self.SeatBillieComboBox.addItem("")
        self.SeatBillieComboBox.addItem("")
        self.SeatBillieComboBox.addItem("")
        self.SeatBillieComboBox.addItem("")
        self.SeatBillieComboBox.addItem("")
        self.SeatBillieComboBox.addItem("")
        self.SeatBillieComboBox.addItem("")
        self.SeatBillieComboBox.addItem("")
        self.SeatBillieComboBox.addItem("")
        self.SeatBillieComboBox.addItem("")
        self.SeatBillieComboBox.addItem("")
        self.SeatBillieComboBox.addItem("")
        self.SeatBillieComboBox.addItem("")
        self.SeatBillieComboBox.addItem("")
        self.SeatBillieComboBox.addItem("")
        self.SeatBillieComboBox.addItem("")
        self.SeatBillieComboBox.addItem("")
        self.SeatBillieComboBox.addItem("")
        self.SeatBillieComboBox.addItem("")
        self.SeatBillieComboBox.addItem("")
        self.SeatBillieComboBox.addItem("")
        self.TotalBillieLabel = QtWidgets.QLabel(self.centralwidget)
        self.TotalBillieLabel.setGeometry(QtCore.QRect(70, 800, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.TotalBillieLabel.setFont(font)
        self.TotalBillieLabel.setStyleSheet("QLabel {\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.TotalBillieLabel.setObjectName("TotalBillieLabel")
        self.TotalBillieLabelValue = QtWidgets.QLabel(self.centralwidget)
        self.TotalBillieLabelValue.setGeometry(QtCore.QRect(330, 800, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.TotalBillieLabelValue.setFont(font)
        self.TotalBillieLabelValue.setStyleSheet("QLabel {\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.TotalBillieLabelValue.setObjectName("TotalBillieLabelValue")
        self.PayBillieBtn = QtWidgets.QPushButton(self.centralwidget)
        self.PayBillieBtn.setEnabled(False)
        self.PayBillieBtn.setGeometry(QtCore.QRect(430, 930, 271, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.PayBillieBtn.setFont(font)
        self.PayBillieBtn.setStyleSheet("\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"\n"
"")
        self.PayBillieBtn.setObjectName("PayBillieBtn")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(330, 620, 191, 41))
        self.lineEdit.setStyleSheet("\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"")
        self.lineEdit.setObjectName("lineEdit")
        BilleiPage.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(BilleiPage)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1920, 26))
        self.menubar.setObjectName("menubar")
        BilleiPage.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(BilleiPage)
        self.statusbar.setObjectName("statusbar")
        BilleiPage.setStatusBar(self.statusbar)

        self.retranslateUi(BilleiPage)
        QtCore.QMetaObject.connectSlotsByName(BilleiPage)

    def retranslateUi(self, BilleiPage):
        _translate = QtCore.QCoreApplication.translate
        BilleiPage.setWindowTitle(_translate("BilleiPage", "MainWindow"))
        self.BillieBackBtn.setText(_translate("BilleiPage", "<"))
        self.DateBillieComboBox.setItemText(0, _translate("BilleiPage", "8 July - Glasgow - OVO Hydro"))
        self.DateBillieComboBox.setItemText(1, _translate("BilleiPage", "10 July - London -The O2 Arena"))
        self.DateBillieComboBox.setItemText(2, _translate("BilleiPage", "11 July - London -The O2 Arena"))
        self.DateBillieComboBox.setItemText(3, _translate("BilleiPage", "13 July - London -The O2 Arena"))
        self.DateBillieComboBox.setItemText(4, _translate("BilleiPage", "14 July - London -The O2 Arena"))
        self.DateBillieComboBox.setItemText(5, _translate("BilleiPage", "16 July - London -The O2 Arena"))
        self.DateBillieComboBox.setItemText(6, _translate("BilleiPage", "17 July - London -The O2 Arena"))
        self.DateBillieComboBox.setItemText(7, _translate("BilleiPage", "19 July - Manchester - Co-op Live"))
        self.DateBillieComboBox.setItemText(8, _translate("BilleiPage", "20 July - Manchester - Co-op Live"))
        self.DateBillieComboBox.setItemText(9, _translate("BilleiPage", "22 July - Manchester - Co-op Live"))
        self.DateBillieComboBox.setItemText(10, _translate("BilleiPage", "23 July - Manchester - Co-op Live"))
        self.DateBillieComboBox.setItemText(11, _translate("BilleiPage", "26 July - Dublin - 3Arena"))
        self.DateBillieComboBox.setItemText(12, _translate("BilleiPage", "27 July - Dublin - 3Arena"))
        self.DateBillieComboBox.setItemText(13, _translate("BilleiPage", "16 August -Saitma(Tokyo) -  Saitama Super Arena"))
        self.DateBillieComboBox.setItemText(14, _translate("BilleiPage", "17 August -Saitma(Tokyo) -  Saitama Super Arena"))
        self.DateBillieComboBox.setItemText(15, _translate("BilleiPage", "9 Octomber - Miami - Kaseya Center"))
        self.DateBillieComboBox.setItemText(16, _translate("BilleiPage", "11 Octomber - Miami - Kaseya Center"))
        self.DateBillieComboBox.setItemText(17, _translate("BilleiPage", "12 Octomber - Miami - Kaseya Center"))
        self.DateBillieComboBox.setItemText(18, _translate("BilleiPage", "14 Octomber - Orlando - Kia Center"))
        self.DateBillieComboBox.setItemText(19, _translate("BilleiPage", "16 Octomber - Raleigh - Lenovo Center"))
        self.DateBillieComboBox.setItemText(20, _translate("BilleiPage", "17 Octomber - Raleigh - Lenovo Center"))
        self.DateBillieComboBox.setItemText(21, _translate("BilleiPage", "19 Octomber - Charlotte -Spectrum Center"))
        self.DateBillieComboBox.setItemText(22, _translate("BilleiPage", "20 Octomber - Charlotte -Spectrum Center"))
        self.DateBillieComboBox.setItemText(23, _translate("BilleiPage", "23 Octomber - Philadelphia - Wells Frago Center"))
        self.DateBillieComboBox.setItemText(24, _translate("BilleiPage", "25 Octomber - Elmont -UBS arena"))
        self.DateBillieComboBox.setItemText(25, _translate("BilleiPage", "26 Octomber - Elmont -UBS arena"))
        self.DateBillieComboBox.setItemText(26, _translate("BilleiPage", "7 November  - New Orleans - Smothie Kind Center"))
        self.DateBillieComboBox.setItemText(27, _translate("BilleiPage", "8 November  - New Orleans - Smothie Kind Center"))
        self.DateBillieComboBox.setItemText(28, _translate("BilleiPage", "10 November - Tulsa - BOK Center"))
        self.DateBillieComboBox.setItemText(29, _translate("BilleiPage", "11 November - Tulsa - BOK Center"))
        self.DateBillieComboBox.setItemText(30, _translate("BilleiPage", "13 November - Austin - Moddy Center ATX"))
        self.DateBillieComboBox.setItemText(31, _translate("BilleiPage", "14 November - Austin - Moddy Center ATX"))
        self.DateBillieComboBox.setItemText(32, _translate("BilleiPage", "18 November - Phoenix -PHX Arena"))
        self.DateBillieComboBox.setItemText(33, _translate("BilleiPage", "19 November - Phoenix -PHX Arena"))
        self.DateBillieComboBox.setItemText(34, _translate("BilleiPage", "22 November -San Francisco - Chase Center"))
        self.DateBillieComboBox.setItemText(35, _translate("BilleiPage", "23 November -San Francisco - Chase Center"))
        self.BilliePriceLabel.setText(_translate("BilleiPage", "Price : 200$"))
        self.DateBillieLabel.setText(_translate("BilleiPage", "Date & City"))
        self.QuantityBillieLabel.setText(_translate("BilleiPage", "Quantity"))
        self.ConfirmBillieBtn.setText(_translate("BilleiPage", "Confirm "))
        self.RowBillieLabel.setText(_translate("BilleiPage", "The Row"))
        self.SeatBilieLabel.setText(_translate("BilleiPage", "The seat"))
        self.RowBillieComboBox.setItemText(0, _translate("BilleiPage", "1"))
        self.RowBillieComboBox.setItemText(1, _translate("BilleiPage", "2"))
        self.RowBillieComboBox.setItemText(2, _translate("BilleiPage", "3"))
        self.RowBillieComboBox.setItemText(3, _translate("BilleiPage", "4"))
        self.RowBillieComboBox.setItemText(4, _translate("BilleiPage", "5"))
        self.RowBillieComboBox.setItemText(5, _translate("BilleiPage", "6"))
        self.RowBillieComboBox.setItemText(6, _translate("BilleiPage", "7"))
        self.RowBillieComboBox.setItemText(7, _translate("BilleiPage", "8"))
        self.RowBillieComboBox.setItemText(8, _translate("BilleiPage", "9"))
        self.RowBillieComboBox.setItemText(9, _translate("BilleiPage", "10"))
        self.RowBillieComboBox.setItemText(10, _translate("BilleiPage", "11"))
        self.RowBillieComboBox.setItemText(11, _translate("BilleiPage", "12"))
        self.RowBillieComboBox.setItemText(12, _translate("BilleiPage", "13"))
        self.RowBillieComboBox.setItemText(13, _translate("BilleiPage", "14"))
        self.RowBillieComboBox.setItemText(14, _translate("BilleiPage", "15"))
        self.RowBillieComboBox.setItemText(15, _translate("BilleiPage", "16"))
        self.RowBillieComboBox.setItemText(16, _translate("BilleiPage", "17"))
        self.RowBillieComboBox.setItemText(17, _translate("BilleiPage", "18"))
        self.RowBillieComboBox.setItemText(18, _translate("BilleiPage", "19"))
        self.RowBillieComboBox.setItemText(19, _translate("BilleiPage", "20"))
        self.RowBillieComboBox.setItemText(20, _translate("BilleiPage", "21"))
        self.RowBillieComboBox.setItemText(21, _translate("BilleiPage", "22"))
        self.RowBillieComboBox.setItemText(22, _translate("BilleiPage", "23"))
        self.RowBillieComboBox.setItemText(23, _translate("BilleiPage", "24"))
        self.RowBillieComboBox.setItemText(24, _translate("BilleiPage", "25"))
        self.RowBillieComboBox.setItemText(25, _translate("BilleiPage", "26"))
        self.RowBillieComboBox.setItemText(26, _translate("BilleiPage", "27"))
        self.RowBillieComboBox.setItemText(27, _translate("BilleiPage", "28"))
        self.RowBillieComboBox.setItemText(28, _translate("BilleiPage", "29"))
        self.RowBillieComboBox.setItemText(29, _translate("BilleiPage", "30"))
        self.SeatBillieComboBox.setItemText(0, _translate("BilleiPage", "1"))
        self.SeatBillieComboBox.setItemText(1, _translate("BilleiPage", "2"))
        self.SeatBillieComboBox.setItemText(2, _translate("BilleiPage", "3"))
        self.SeatBillieComboBox.setItemText(3, _translate("BilleiPage", "4"))
        self.SeatBillieComboBox.setItemText(4, _translate("BilleiPage", "5"))
        self.SeatBillieComboBox.setItemText(5, _translate("BilleiPage", "6"))
        self.SeatBillieComboBox.setItemText(6, _translate("BilleiPage", "7"))
        self.SeatBillieComboBox.setItemText(7, _translate("BilleiPage", "8"))
        self.SeatBillieComboBox.setItemText(8, _translate("BilleiPage", "9"))
        self.SeatBillieComboBox.setItemText(9, _translate("BilleiPage", "10"))
        self.SeatBillieComboBox.setItemText(10, _translate("BilleiPage", "11"))
        self.SeatBillieComboBox.setItemText(11, _translate("BilleiPage", "12"))
        self.SeatBillieComboBox.setItemText(12, _translate("BilleiPage", "13"))
        self.SeatBillieComboBox.setItemText(13, _translate("BilleiPage", "14"))
        self.SeatBillieComboBox.setItemText(14, _translate("BilleiPage", "15"))
        self.SeatBillieComboBox.setItemText(15, _translate("BilleiPage", "16"))
        self.SeatBillieComboBox.setItemText(16, _translate("BilleiPage", "17"))
        self.SeatBillieComboBox.setItemText(17, _translate("BilleiPage", "18"))
        self.SeatBillieComboBox.setItemText(18, _translate("BilleiPage", "19"))
        self.SeatBillieComboBox.setItemText(19, _translate("BilleiPage", "20"))
        self.SeatBillieComboBox.setItemText(20, _translate("BilleiPage", "21"))
        self.SeatBillieComboBox.setItemText(21, _translate("BilleiPage", "22"))
        self.SeatBillieComboBox.setItemText(22, _translate("BilleiPage", "23"))
        self.SeatBillieComboBox.setItemText(23, _translate("BilleiPage", "24"))
        self.SeatBillieComboBox.setItemText(24, _translate("BilleiPage", "25"))
        self.SeatBillieComboBox.setItemText(25, _translate("BilleiPage", "26"))
        self.SeatBillieComboBox.setItemText(26, _translate("BilleiPage", "27"))
        self.SeatBillieComboBox.setItemText(27, _translate("BilleiPage", "28"))
        self.SeatBillieComboBox.setItemText(28, _translate("BilleiPage", "29"))
        self.SeatBillieComboBox.setItemText(29, _translate("BilleiPage", "30"))
        self.TotalBillieLabel.setText(_translate("BilleiPage", "In Total"))
        self.TotalBillieLabelValue.setText(_translate("BilleiPage", "0$"))
        self.PayBillieBtn.setText(_translate("BilleiPage", "Choose The Quantity First"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    BilleiPage = QtWidgets.QMainWindow()
    ui = Ui_BilleiPage()
    ui.setupUi(BilleiPage)
    BilleiPage.show()
    sys.exit(app.exec_())
