# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BookTheTicketPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BookTheTicketPage(object):
    def setupUi(self, BookTheTicketPage):
        BookTheTicketPage.setObjectName("BookTheTicketPage")
        BookTheTicketPage.resize(1920, 1080)
        BookTheTicketPage.setMinimumSize(QtCore.QSize(1920, 1080))
        BookTheTicketPage.setMaximumSize(QtCore.QSize(1920, 1080))
        self.centralwidget = QtWidgets.QWidget(BookTheTicketPage)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 50, 1920, 1080))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(1920, 1080))
        self.label.setMaximumSize(QtCore.QSize(1920, 1080))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("BookPagePic.png"))
        self.label.setObjectName("label")
        self.BTTBackBtn = QtWidgets.QPushButton(self.centralwidget)
        self.BTTBackBtn.setGeometry(QtCore.QRect(1750, 940, 151, 71))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.BTTBackBtn.setFont(font)
        self.BTTBackBtn.setStyleSheet("\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"\n"
"")
        self.BTTBackBtn.setObjectName("BTTBackBtn")
        self.HMHASbtn = QtWidgets.QPushButton(self.centralwidget)
        self.HMHASbtn.setGeometry(QtCore.QRect(210, 720, 311, 71))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.HMHASbtn.setFont(font)
        self.HMHASbtn.setStyleSheet("\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"\n"
"")
        self.HMHASbtn.setObjectName("HMHASbtn")
        self.LDRUKBtn = QtWidgets.QPushButton(self.centralwidget)
        self.LDRUKBtn.setGeometry(QtCore.QRect(620, 720, 311, 71))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.LDRUKBtn.setFont(font)
        self.LDRUKBtn.setStyleSheet("\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"\n"
"")
        self.LDRUKBtn.setObjectName("LDRUKBtn")
        self.AHTDBtn = QtWidgets.QPushButton(self.centralwidget)
        self.AHTDBtn.setGeometry(QtCore.QRect(1020, 720, 321, 71))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.AHTDBtn.setFont(font)
        self.AHTDBtn.setStyleSheet("\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"\n"
"")
        self.AHTDBtn.setObjectName("AHTDBtn")
        self.CCBtn = QtWidgets.QPushButton(self.centralwidget)
        self.CCBtn.setGeometry(QtCore.QRect(1400, 720, 321, 71))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.CCBtn.setFont(font)
        self.CCBtn.setStyleSheet("\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"\n"
"")
        self.CCBtn.setObjectName("CCBtn")
        BookTheTicketPage.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(BookTheTicketPage)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1920, 26))
        self.menubar.setObjectName("menubar")
        BookTheTicketPage.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(BookTheTicketPage)
        self.statusbar.setObjectName("statusbar")
        BookTheTicketPage.setStatusBar(self.statusbar)

        self.retranslateUi(BookTheTicketPage)
        QtCore.QMetaObject.connectSlotsByName(BookTheTicketPage)

    def retranslateUi(self, BookTheTicketPage):
        _translate = QtCore.QCoreApplication.translate
        BookTheTicketPage.setWindowTitle(_translate("BookTheTicketPage", "MainWindow"))
        self.BTTBackBtn.setText(_translate("BookTheTicketPage", "<"))
        self.HMHASbtn.setText(_translate("BookTheTicketPage", "Hit Me Hard And Soft Tour"))
        self.LDRUKBtn.setText(_translate("BookTheTicketPage", "LDR UK Tour"))
        self.AHTDBtn.setText(_translate("BookTheTicketPage", "After Hours Till Down Tour"))
        self.CCBtn.setText(_translate("BookTheTicketPage", "Cowboy Carter Tour"))
