# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'InventoryPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_InventoryPage(object):
    def setupUi(self, InventoryPage):
        InventoryPage.setObjectName("InventoryPage")
        InventoryPage.resize(1920, 1080)
        InventoryPage.setMinimumSize(QtCore.QSize(1920, 1080))
        InventoryPage.setMaximumSize(QtCore.QSize(1920, 1080))
        self.centralwidget = QtWidgets.QWidget(InventoryPage)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1920, 1080))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(1920, 1080))
        self.label.setMaximumSize(QtCore.QSize(1920, 1080))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("InventoryPic.png"))
        self.label.setObjectName("label")
        self.DataLabel = QtWidgets.QLabel(self.centralwidget)
        self.DataLabel.setGeometry(QtCore.QRect(210, 320, 1491, 591))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.DataLabel.setFont(font)
        self.DataLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.DataLabel.setStyleSheet("QLabel {\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.DataLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.DataLabel.setObjectName("DataLabel")
        self.InventoryBackBtn = QtWidgets.QPushButton(self.centralwidget)
        self.InventoryBackBtn.setGeometry(QtCore.QRect(1750, 940, 151, 71))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.InventoryBackBtn.setFont(font)
        self.InventoryBackBtn.setStyleSheet("\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"\n"
"")
        self.InventoryBackBtn.setObjectName("InventoryBackBtn")
        InventoryPage.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(InventoryPage)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1920, 26))
        self.menubar.setObjectName("menubar")
        InventoryPage.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(InventoryPage)
        self.statusbar.setObjectName("statusbar")
        InventoryPage.setStatusBar(self.statusbar)

        self.retranslateUi(InventoryPage)
        QtCore.QMetaObject.connectSlotsByName(InventoryPage)

    def retranslateUi(self, InventoryPage):
        _translate = QtCore.QCoreApplication.translate
        InventoryPage.setWindowTitle(_translate("InventoryPage", "MainWindow"))
        self.DataLabel.setText(_translate("InventoryPage", "No Data"))
        self.InventoryBackBtn.setText(_translate("InventoryPage", "<"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    InventoryPage = QtWidgets.QMainWindow()
    ui = Ui_InventoryPage()
    ui.setupUi(InventoryPage)
    InventoryPage.show()
    sys.exit(app.exec_())
