# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LanaPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LanaPage(object):
    def setupUi(self, LanaPage):
        LanaPage.setObjectName("LanaPage")
        LanaPage.resize(1920, 1080)
        LanaPage.setMinimumSize(QtCore.QSize(1920, 1080))
        LanaPage.setMaximumSize(QtCore.QSize(1920, 1080))
        self.centralwidget = QtWidgets.QWidget(LanaPage)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, -40, 1920, 1080))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(1920, 1080))
        self.label.setMaximumSize(QtCore.QSize(1920, 1080))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("LanaPage.png"))
        self.label.setObjectName("label")
        self.LanaBackBtn = QtWidgets.QPushButton(self.centralwidget)
        self.LanaBackBtn.setGeometry(QtCore.QRect(1750, 940, 151, 71))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.LanaBackBtn.setFont(font)
        self.LanaBackBtn.setStyleSheet("\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"\n"
"")
        self.LanaBackBtn.setObjectName("LanaBackBtn")
        self.DateLanaComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.DateLanaComboBox.setGeometry(QtCore.QRect(330, 560, 191, 41))
        self.DateLanaComboBox.setStyleSheet("\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"\n"
"")
        self.DateLanaComboBox.setObjectName("DateLanaComboBox")
        self.DateLanaComboBox.addItem("")
        self.DateLanaComboBox.addItem("")
        self.DateLanaComboBox.addItem("")
        self.DateLanaComboBox.addItem("")
        self.DateLanaComboBox.addItem("")
        self.DateLanaComboBox.addItem("")
        self.LanaPriceLabel = QtWidgets.QLabel(self.centralwidget)
        self.LanaPriceLabel.setGeometry(QtCore.QRect(70, 500, 451, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.LanaPriceLabel.setFont(font)
        self.LanaPriceLabel.setStyleSheet("QLabel {\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.LanaPriceLabel.setObjectName("LanaPriceLabel")
        self.DateLanaLabel = QtWidgets.QLabel(self.centralwidget)
        self.DateLanaLabel.setGeometry(QtCore.QRect(70, 560, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.DateLanaLabel.setFont(font)
        self.DateLanaLabel.setStyleSheet("QLabel {\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.DateLanaLabel.setObjectName("DateLanaLabel")
        self.QuantityLanaLabel = QtWidgets.QLabel(self.centralwidget)
        self.QuantityLanaLabel.setGeometry(QtCore.QRect(70, 620, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.QuantityLanaLabel.setFont(font)
        self.QuantityLanaLabel.setStyleSheet("QLabel {\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.QuantityLanaLabel.setObjectName("QuantityLanaLabel")
        self.ConfirmLanaBtn = QtWidgets.QPushButton(self.centralwidget)
        self.ConfirmLanaBtn.setGeometry(QtCore.QRect(250, 850, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ConfirmLanaBtn.setFont(font)
        self.ConfirmLanaBtn.setStyleSheet("\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"\n"
"")
        self.ConfirmLanaBtn.setObjectName("ConfirmLanaBtn")
        self.RowLanaLabel = QtWidgets.QLabel(self.centralwidget)
        self.RowLanaLabel.setGeometry(QtCore.QRect(70, 680, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.RowLanaLabel.setFont(font)
        self.RowLanaLabel.setStyleSheet("QLabel {\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.RowLanaLabel.setObjectName("RowLanaLabel")
        self.SeatLanaLabel = QtWidgets.QLabel(self.centralwidget)
        self.SeatLanaLabel.setGeometry(QtCore.QRect(70, 740, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.SeatLanaLabel.setFont(font)
        self.SeatLanaLabel.setStyleSheet("QLabel {\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.SeatLanaLabel.setObjectName("SeatLanaLabel")
        self.RowLanaComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.RowLanaComboBox.setGeometry(QtCore.QRect(330, 680, 191, 41))
        self.RowLanaComboBox.setStyleSheet("\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"\n"
"")
        self.RowLanaComboBox.setObjectName("RowLanaComboBox")
        self.RowLanaComboBox.addItem("")
        self.RowLanaComboBox.addItem("")
        self.RowLanaComboBox.addItem("")
        self.RowLanaComboBox.addItem("")
        self.RowLanaComboBox.addItem("")
        self.RowLanaComboBox.addItem("")
        self.RowLanaComboBox.addItem("")
        self.RowLanaComboBox.addItem("")
        self.RowLanaComboBox.addItem("")
        self.RowLanaComboBox.addItem("")
        self.RowLanaComboBox.addItem("")
        self.RowLanaComboBox.addItem("")
        self.RowLanaComboBox.addItem("")
        self.RowLanaComboBox.addItem("")
        self.RowLanaComboBox.addItem("")
        self.RowLanaComboBox.addItem("")
        self.RowLanaComboBox.addItem("")
        self.RowLanaComboBox.addItem("")
        self.RowLanaComboBox.addItem("")
        self.RowLanaComboBox.addItem("")
        self.RowLanaComboBox.addItem("")
        self.RowLanaComboBox.addItem("")
        self.RowLanaComboBox.addItem("")
        self.RowLanaComboBox.addItem("")
        self.RowLanaComboBox.addItem("")
        self.RowLanaComboBox.addItem("")
        self.RowLanaComboBox.addItem("")
        self.RowLanaComboBox.addItem("")
        self.RowLanaComboBox.addItem("")
        self.RowLanaComboBox.addItem("")
        self.SeatLanaComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.SeatLanaComboBox.setGeometry(QtCore.QRect(330, 740, 191, 41))
        self.SeatLanaComboBox.setStyleSheet("\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"\n"
"")
        self.SeatLanaComboBox.setObjectName("SeatLanaComboBox")
        self.SeatLanaComboBox.addItem("")
        self.SeatLanaComboBox.addItem("")
        self.SeatLanaComboBox.addItem("")
        self.SeatLanaComboBox.addItem("")
        self.SeatLanaComboBox.addItem("")
        self.SeatLanaComboBox.addItem("")
        self.SeatLanaComboBox.addItem("")
        self.SeatLanaComboBox.addItem("")
        self.SeatLanaComboBox.addItem("")
        self.SeatLanaComboBox.addItem("")
        self.SeatLanaComboBox.addItem("")
        self.SeatLanaComboBox.addItem("")
        self.SeatLanaComboBox.addItem("")
        self.SeatLanaComboBox.addItem("")
        self.SeatLanaComboBox.addItem("")
        self.SeatLanaComboBox.addItem("")
        self.SeatLanaComboBox.addItem("")
        self.SeatLanaComboBox.addItem("")
        self.SeatLanaComboBox.addItem("")
        self.SeatLanaComboBox.addItem("")
        self.SeatLanaComboBox.addItem("")
        self.SeatLanaComboBox.addItem("")
        self.SeatLanaComboBox.addItem("")
        self.SeatLanaComboBox.addItem("")
        self.SeatLanaComboBox.addItem("")
        self.SeatLanaComboBox.addItem("")
        self.SeatLanaComboBox.addItem("")
        self.SeatLanaComboBox.addItem("")
        self.SeatLanaComboBox.addItem("")
        self.SeatLanaComboBox.addItem("")
        self.TotalLanaLabel = QtWidgets.QLabel(self.centralwidget)
        self.TotalLanaLabel.setGeometry(QtCore.QRect(70, 800, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.TotalLanaLabel.setFont(font)
        self.TotalLanaLabel.setStyleSheet("QLabel {\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.TotalLanaLabel.setObjectName("TotalLanaLabel")
        self.TotalLanaLabelValue = QtWidgets.QLabel(self.centralwidget)
        self.TotalLanaLabelValue.setGeometry(QtCore.QRect(330, 800, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.TotalLanaLabelValue.setFont(font)
        self.TotalLanaLabelValue.setStyleSheet("QLabel {\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.TotalLanaLabelValue.setObjectName("TotalLanaLabelValue")
        self.PayLanaBtn = QtWidgets.QPushButton(self.centralwidget)
        self.PayLanaBtn.setEnabled(False)
        self.PayLanaBtn.setGeometry(QtCore.QRect(430, 930, 271, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.PayLanaBtn.setFont(font)
        self.PayLanaBtn.setStyleSheet("\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"\n"
"")
        self.PayLanaBtn.setObjectName("PayLanaBtn")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(330, 620, 191, 41))
        self.lineEdit.setStyleSheet("\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"")
        self.lineEdit.setObjectName("lineEdit")
        LanaPage.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(LanaPage)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1920, 26))
        self.menubar.setObjectName("menubar")
        LanaPage.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(LanaPage)
        self.statusbar.setObjectName("statusbar")
        LanaPage.setStatusBar(self.statusbar)

        self.retranslateUi(LanaPage)
        QtCore.QMetaObject.connectSlotsByName(LanaPage)

    def retranslateUi(self, LanaPage):
        _translate = QtCore.QCoreApplication.translate
        LanaPage.setWindowTitle(_translate("LanaPage", "MainWindow"))
        self.LanaBackBtn.setText(_translate("LanaPage", "<"))
        self.DateLanaComboBox.setItemText(0, _translate("LanaPage", "23 June - Cardiff - Principality Stadium"))
        self.DateLanaComboBox.setItemText(1, _translate("LanaPage", "26 June - Glasgow - Hampden Park"))
        self.DateLanaComboBox.setItemText(2, _translate("LanaPage", "28 June - Liverpool - Anfield Stadium"))
        self.DateLanaComboBox.setItemText(3, _translate("LanaPage", "30 June - Dublin - Aviva Stadium"))
        self.DateLanaComboBox.setItemText(4, _translate("LanaPage", "3 July - London - Wembley Staidum"))
        self.DateLanaComboBox.setItemText(5, _translate("LanaPage", "4 July - London - Wembley Staidum"))
        self.LanaPriceLabel.setText(_translate("LanaPage", "Price : 180$"))
        self.DateLanaLabel.setText(_translate("LanaPage", "Date & City"))
        self.QuantityLanaLabel.setText(_translate("LanaPage", "Quantity"))
        self.ConfirmLanaBtn.setText(_translate("LanaPage", "Confirm "))
        self.RowLanaLabel.setText(_translate("LanaPage", "The Row"))
        self.SeatLanaLabel.setText(_translate("LanaPage", "The seat"))
        self.RowLanaComboBox.setItemText(0, _translate("LanaPage", "1"))
        self.RowLanaComboBox.setItemText(1, _translate("LanaPage", "2"))
        self.RowLanaComboBox.setItemText(2, _translate("LanaPage", "3"))
        self.RowLanaComboBox.setItemText(3, _translate("LanaPage", "4"))
        self.RowLanaComboBox.setItemText(4, _translate("LanaPage", "5"))
        self.RowLanaComboBox.setItemText(5, _translate("LanaPage", "6"))
        self.RowLanaComboBox.setItemText(6, _translate("LanaPage", "7"))
        self.RowLanaComboBox.setItemText(7, _translate("LanaPage", "8"))
        self.RowLanaComboBox.setItemText(8, _translate("LanaPage", "9"))
        self.RowLanaComboBox.setItemText(9, _translate("LanaPage", "10"))
        self.RowLanaComboBox.setItemText(10, _translate("LanaPage", "11"))
        self.RowLanaComboBox.setItemText(11, _translate("LanaPage", "12"))
        self.RowLanaComboBox.setItemText(12, _translate("LanaPage", "13"))
        self.RowLanaComboBox.setItemText(13, _translate("LanaPage", "14"))
        self.RowLanaComboBox.setItemText(14, _translate("LanaPage", "15"))
        self.RowLanaComboBox.setItemText(15, _translate("LanaPage", "16"))
        self.RowLanaComboBox.setItemText(16, _translate("LanaPage", "17"))
        self.RowLanaComboBox.setItemText(17, _translate("LanaPage", "18"))
        self.RowLanaComboBox.setItemText(18, _translate("LanaPage", "19"))
        self.RowLanaComboBox.setItemText(19, _translate("LanaPage", "20"))
        self.RowLanaComboBox.setItemText(20, _translate("LanaPage", "21"))
        self.RowLanaComboBox.setItemText(21, _translate("LanaPage", "22"))
        self.RowLanaComboBox.setItemText(22, _translate("LanaPage", "23"))
        self.RowLanaComboBox.setItemText(23, _translate("LanaPage", "24"))
        self.RowLanaComboBox.setItemText(24, _translate("LanaPage", "25"))
        self.RowLanaComboBox.setItemText(25, _translate("LanaPage", "26"))
        self.RowLanaComboBox.setItemText(26, _translate("LanaPage", "27"))
        self.RowLanaComboBox.setItemText(27, _translate("LanaPage", "28"))
        self.RowLanaComboBox.setItemText(28, _translate("LanaPage", "29"))
        self.RowLanaComboBox.setItemText(29, _translate("LanaPage", "30"))
        self.SeatLanaComboBox.setItemText(0, _translate("LanaPage", "1"))
        self.SeatLanaComboBox.setItemText(1, _translate("LanaPage", "2"))
        self.SeatLanaComboBox.setItemText(2, _translate("LanaPage", "3"))
        self.SeatLanaComboBox.setItemText(3, _translate("LanaPage", "4"))
        self.SeatLanaComboBox.setItemText(4, _translate("LanaPage", "5"))
        self.SeatLanaComboBox.setItemText(5, _translate("LanaPage", "6"))
        self.SeatLanaComboBox.setItemText(6, _translate("LanaPage", "7"))
        self.SeatLanaComboBox.setItemText(7, _translate("LanaPage", "8"))
        self.SeatLanaComboBox.setItemText(8, _translate("LanaPage", "9"))
        self.SeatLanaComboBox.setItemText(9, _translate("LanaPage", "10"))
        self.SeatLanaComboBox.setItemText(10, _translate("LanaPage", "11"))
        self.SeatLanaComboBox.setItemText(11, _translate("LanaPage", "12"))
        self.SeatLanaComboBox.setItemText(12, _translate("LanaPage", "13"))
        self.SeatLanaComboBox.setItemText(13, _translate("LanaPage", "14"))
        self.SeatLanaComboBox.setItemText(14, _translate("LanaPage", "15"))
        self.SeatLanaComboBox.setItemText(15, _translate("LanaPage", "16"))
        self.SeatLanaComboBox.setItemText(16, _translate("LanaPage", "17"))
        self.SeatLanaComboBox.setItemText(17, _translate("LanaPage", "18"))
        self.SeatLanaComboBox.setItemText(18, _translate("LanaPage", "19"))
        self.SeatLanaComboBox.setItemText(19, _translate("LanaPage", "20"))
        self.SeatLanaComboBox.setItemText(20, _translate("LanaPage", "21"))
        self.SeatLanaComboBox.setItemText(21, _translate("LanaPage", "22"))
        self.SeatLanaComboBox.setItemText(22, _translate("LanaPage", "23"))
        self.SeatLanaComboBox.setItemText(23, _translate("LanaPage", "24"))
        self.SeatLanaComboBox.setItemText(24, _translate("LanaPage", "25"))
        self.SeatLanaComboBox.setItemText(25, _translate("LanaPage", "26"))
        self.SeatLanaComboBox.setItemText(26, _translate("LanaPage", "27"))
        self.SeatLanaComboBox.setItemText(27, _translate("LanaPage", "28"))
        self.SeatLanaComboBox.setItemText(28, _translate("LanaPage", "29"))
        self.SeatLanaComboBox.setItemText(29, _translate("LanaPage", "30"))
        self.TotalLanaLabel.setText(_translate("LanaPage", "In Total"))
        self.TotalLanaLabelValue.setText(_translate("LanaPage", "0$"))
        self.PayLanaBtn.setText(_translate("LanaPage", "Choose The Quantity First"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LanaPage = QtWidgets.QMainWindow()
    ui = Ui_LanaPage()
    ui.setupUi(LanaPage)
    LanaPage.show()
    sys.exit(app.exec_())
