# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LogInPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets, uic


class Ui_LogInPage(object):
    def setupUi(self, LogInPage):
        LogInPage.setObjectName("LogInPage")
        LogInPage.resize(1920, 1080)
        LogInPage.setMinimumSize(QtCore.QSize(1920, 1080))
        LogInPage.setMaximumSize(QtCore.QSize(1920, 1080))
        self.centralwidget = QtWidgets.QWidget(LogInPage)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1920, 1080))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(1920, 1080))
        self.label.setMaximumSize(QtCore.QSize(1920, 1080))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("LogInPic.png"))
        self.label.setObjectName("label")
        self.LogInLabel = QtWidgets.QLabel(self.centralwidget)
        self.LogInLabel.setGeometry(QtCore.QRect(500, 230, 911, 591))
        self.LogInLabel.setStyleSheet("background-color: rgb(90, 24, 154);\n"
"border-radius: 30px;")
        self.LogInLabel.setText("")
        self.LogInLabel.setObjectName("LogInLabel")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(870, 230, 191, 71))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic")
        font.setPointSize(26)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(223, 126, 255);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(750, 280, 641, 71))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(223, 126, 255);")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(550, 380, 291, 71))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic")
        font.setPointSize(26)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(223, 126, 255);")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(550, 500, 291, 71))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic")
        font.setPointSize(26)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(223, 126, 255);")
        self.label_6.setObjectName("label_6")
        self.UsernameInput = QtWidgets.QLineEdit(self.centralwidget)
        self.UsernameInput.setGeometry(QtCore.QRect(540, 450, 821, 31))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(10)
        self.UsernameInput.setFont(font)
        self.UsernameInput.setStyleSheet("background-color: rgb(171, 119, 231);\n"
"border-radius: 15px;")
        self.UsernameInput.setText("")
        self.UsernameInput.setObjectName("UsernameInput")
        self.PasswordInput = QtWidgets.QLineEdit(self.centralwidget)
        self.PasswordInput.setGeometry(QtCore.QRect(540, 570, 821, 31))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(10)
        self.PasswordInput.setFont(font)
        self.PasswordInput.setStyleSheet("background-color: rgb(171, 119, 231);\n"
"border-radius: 15px;")
        self.PasswordInput.setText("")
        self.PasswordInput.setObjectName("PasswordInput")
        self.LogInBtn = QtWidgets.QPushButton(self.centralwidget)
        self.LogInBtn.setGeometry(QtCore.QRect(810, 720, 291, 81))
        self.LogInBtn.setStyleSheet("QPushButton {\n"
"    font: 20pt \"Arial Rounded MT Bold\";\n"
"    font: 75 10pt \"Georgia\";\n"
"    background-color: rgb(171, 119, 231);\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 40px;\n"
"    \n"
"}\n"
"\n"
"\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(131, 79, 191);\n"
"}\n"
"\n"
"\n"
"")
        self.LogInBtn.setObjectName("LogInBtn")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(700, 630, 801, 31))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(223, 126, 255);")
        self.label_7.setObjectName("label_7")
        self.AgreementCheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.AgreementCheckBox.setGeometry(QtCore.QRect(1070, 630, 101, 31))
        self.AgreementCheckBox.setStyleSheet("color: rgb(223, 126, 255);\n"
"font: 8pt \"MS Shell Dlg 2\";")
        self.AgreementCheckBox.setText("")
        self.AgreementCheckBox.setObjectName("AgreementCheckBox")
        self.ErrorLabel = QtWidgets.QLabel(self.centralwidget)
        self.ErrorLabel.setGeometry(QtCore.QRect(580, 680, 801, 31))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic")
        font.setPointSize(12)
        self.ErrorLabel.setFont(font)
        self.ErrorLabel.setStyleSheet("color: rgb(170, 0, 0);")
        self.ErrorLabel.setText("")
        self.ErrorLabel.setObjectName("ErrorLabel")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(760, 840, 801, 31))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic")
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(223, 126, 255);")
        self.label_8.setObjectName("label_8")
        self.SignUpPagebtn = QtWidgets.QPushButton(self.centralwidget)
        self.SignUpPagebtn.setGeometry(QtCore.QRect(1000, 840, 141, 31))
        self.SignUpPagebtn.setStyleSheet("QPushButton {\n"
"    font: 20pt \"Arial Rounded MT Bold\";\n"
"    font: 75 10pt \"Georgia\";\n"
"    background-color: rgb(171, 119, 231);\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    \n"
"}\n"
"\n"
"\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(131, 79, 191);\n"
"}\n"
"\n"
"\n"
"")
        self.SignUpPagebtn.setObjectName("SignUpPagebtn")
        self.label.raise_()
        self.LogInLabel.raise_()
        self.UsernameInput.raise_()
        self.PasswordInput.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.LogInBtn.raise_()
        self.label_7.raise_()
        self.AgreementCheckBox.raise_()
        self.ErrorLabel.raise_()
        self.label_8.raise_()
        self.SignUpPagebtn.raise_()
        LogInPage.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(LogInPage)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1920, 26))
        self.menubar.setObjectName("menubar")
        LogInPage.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(LogInPage)
        self.statusbar.setObjectName("statusbar")
        LogInPage.setStatusBar(self.statusbar)

        self.retranslateUi(LogInPage)
        QtCore.QMetaObject.connectSlotsByName(LogInPage)

    def retranslateUi(self, LogInPage):
        _translate = QtCore.QCoreApplication.translate
        LogInPage.setWindowTitle(_translate("LogInPage", "MainWindow"))
        self.label_3.setText(_translate("LogInPage", "Log In To"))
        self.label_4.setText(_translate("LogInPage", "Echochamber"))
        self.label_5.setText(_translate("LogInPage", "Username"))
        self.label_6.setText(_translate("LogInPage", "Password"))
        self.LogInBtn.setText(_translate("LogInPage", "Log In"))
        self.label_7.setText(_translate("LogInPage", "Do you agree to the terms and policies?"))
        self.label_8.setText(_translate("LogInPage", "Don\'t have an account?"))
        self.SignUpPagebtn.setText(_translate("LogInPage", "Sign Up"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LogInPage = QtWidgets.QMainWindow()
    ui = Ui_LogInPage()
    ui.setupUi(LogInPage)
    LogInPage.show()
    sys.exit(app.exec_())
