# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainPage(object):
    def setupUi(self, MainPage):
        MainPage.setObjectName("MainPage")
        MainPage.resize(1920, 1080)
        MainPage.setMinimumSize(QtCore.QSize(1920, 1080))
        MainPage.setMaximumSize(QtCore.QSize(1920, 1080))
        self.centralwidget = QtWidgets.QWidget(MainPage)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1920, 1080))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(1920, 1080))
        self.label.setMaximumSize(QtCore.QSize(1920, 1080))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("MainPagePic.png"))
        self.label.setObjectName("label")
        self.UsernameLabel = QtWidgets.QLabel(self.centralwidget)
        self.UsernameLabel.setGeometry(QtCore.QRect(1380, 70, 291, 71))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.UsernameLabel.setFont(font)
        self.UsernameLabel.setStyleSheet("QLabel {\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.UsernameLabel.setObjectName("UsernameLabel")
        self.InventorLabel = QtWidgets.QLabel(self.centralwidget)
        self.InventorLabel.setGeometry(QtCore.QRect(290, 380, 291, 71))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.InventorLabel.setFont(font)
        self.InventorLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.InventorLabel.setAutoFillBackground(False)
        self.InventorLabel.setStyleSheet("QLabel {\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.InventorLabel.setScaledContents(False)
        self.InventorLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.InventorLabel.setWordWrap(False)
        self.InventorLabel.setOpenExternalLinks(False)
        self.InventorLabel.setObjectName("InventorLabel")
        self.TicketLabel = QtWidgets.QLabel(self.centralwidget)
        self.TicketLabel.setGeometry(QtCore.QRect(820, 380, 291, 71))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.TicketLabel.setFont(font)
        self.TicketLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.TicketLabel.setAutoFillBackground(False)
        self.TicketLabel.setStyleSheet("QLabel {\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.TicketLabel.setScaledContents(False)
        self.TicketLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.TicketLabel.setWordWrap(False)
        self.TicketLabel.setOpenExternalLinks(False)
        self.TicketLabel.setObjectName("TicketLabel")
        self.RecLabel = QtWidgets.QLabel(self.centralwidget)
        self.RecLabel.setGeometry(QtCore.QRect(1330, 370, 291, 71))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.RecLabel.setFont(font)
        self.RecLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.RecLabel.setAutoFillBackground(False)
        self.RecLabel.setStyleSheet("QLabel {\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.RecLabel.setScaledContents(False)
        self.RecLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.RecLabel.setWordWrap(False)
        self.RecLabel.setOpenExternalLinks(False)
        self.RecLabel.setObjectName("RecLabel")
        self.UsernameLabel_2 = QtWidgets.QLabel(self.centralwidget)
        self.UsernameLabel_2.setGeometry(QtCore.QRect(640, 940, 321, 71))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.UsernameLabel_2.setFont(font)
        self.UsernameLabel_2.setStyleSheet("QLabel {\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.UsernameLabel_2.setObjectName("UsernameLabel_2")
        self.SignOutbtn = QtWidgets.QPushButton(self.centralwidget)
        self.SignOutbtn.setGeometry(QtCore.QRect(1080, 940, 151, 71))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.SignOutbtn.setFont(font)
        self.SignOutbtn.setStyleSheet("\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"\n"
"")
        self.SignOutbtn.setObjectName("SignOutbtn")
        self.InventoryBtn = QtWidgets.QPushButton(self.centralwidget)
        self.InventoryBtn.setGeometry(QtCore.QRect(310, 770, 261, 71))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.InventoryBtn.setFont(font)
        self.InventoryBtn.setStyleSheet("\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"\n"
"")
        self.InventoryBtn.setObjectName("InventoryBtn")
        self.BookBtn = QtWidgets.QPushButton(self.centralwidget)
        self.BookBtn.setGeometry(QtCore.QRect(830, 770, 261, 71))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.BookBtn.setFont(font)
        self.BookBtn.setStyleSheet("\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"\n"
"")
        self.BookBtn.setObjectName("BookBtn")
        self.RecBtn = QtWidgets.QPushButton(self.centralwidget)
        self.RecBtn.setGeometry(QtCore.QRect(1350, 780, 261, 71))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.RecBtn.setFont(font)
        self.RecBtn.setStyleSheet("\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"\n"
"")
        self.RecBtn.setObjectName("RecBtn")
        MainPage.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainPage)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1920, 26))
        self.menubar.setObjectName("menubar")
        MainPage.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainPage)
        self.statusbar.setObjectName("statusbar")
        MainPage.setStatusBar(self.statusbar)

        self.retranslateUi(MainPage)
        QtCore.QMetaObject.connectSlotsByName(MainPage)

    def retranslateUi(self, MainPage):
        _translate = QtCore.QCoreApplication.translate
        MainPage.setWindowTitle(_translate("MainPage", "MainWindow"))
        self.UsernameLabel.setText(_translate("MainPage", "USERNAME"))
        self.InventorLabel.setText(_translate("MainPage", "Inventory"))
        self.TicketLabel.setText(_translate("MainPage", "Book The Ticket"))
        self.RecLabel.setText(_translate("MainPage", "Recomendations"))
        self.UsernameLabel_2.setText(_translate("MainPage", "Do you want to leave the account?"))
        self.SignOutbtn.setText(_translate("MainPage", "Sign Out"))
        self.InventoryBtn.setText(_translate("MainPage", "Check it out"))
        self.BookBtn.setText(_translate("MainPage", "Check it out"))
        self.RecBtn.setText(_translate("MainPage", "Check it out"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainPage = QtWidgets.QMainWindow()
    ui = Ui_MainPage()
    ui.setupUi(MainPage)
    MainPage.show()
    sys.exit(app.exec_())
