# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RecomendationsPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RecPage(object):
    def setupUi(self, RecPage):
        RecPage.setObjectName("RecPage")
        RecPage.resize(1920, 1080)
        RecPage.setMinimumSize(QtCore.QSize(1920, 1080))
        RecPage.setMaximumSize(QtCore.QSize(1920, 1080))
        self.centralwidget = QtWidgets.QWidget(RecPage)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-10, -20, 1920, 1080))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(1920, 1080))
        self.label.setMaximumSize(QtCore.QSize(1920, 1080))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("RecPagePic.png"))
        self.label.setObjectName("label")
        self.RecBackBtn = QtWidgets.QPushButton(self.centralwidget)
        self.RecBackBtn.setGeometry(QtCore.QRect(1750, 940, 151, 71))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.RecBackBtn.setFont(font)
        self.RecBackBtn.setStyleSheet("\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"\n"
"")
        self.RecBackBtn.setObjectName("RecBackBtn")
        self.GenerateBtn = QtWidgets.QPushButton(self.centralwidget)
        self.GenerateBtn.setGeometry(QtCore.QRect(430, 400, 311, 71))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.GenerateBtn.setFont(font)
        self.GenerateBtn.setStyleSheet("\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"\n"
"")
        self.GenerateBtn.setObjectName("GenerateBtn")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(240, 300, 681, 71))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel {\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 30px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.TopSongsLabel = QtWidgets.QLabel(self.centralwidget)
        self.TopSongsLabel.setGeometry(QtCore.QRect(210, 480, 791, 391))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.TopSongsLabel.setFont(font)
        self.TopSongsLabel.setStyleSheet("QLabel {\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 30px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.TopSongsLabel.setText("")
        self.TopSongsLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.TopSongsLabel.setObjectName("TopSongsLabel")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(1040, 300, 681, 71))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("QLabel {\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 30px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        RecPage.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(RecPage)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1920, 26))
        self.menubar.setObjectName("menubar")
        RecPage.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(RecPage)
        self.statusbar.setObjectName("statusbar")
        RecPage.setStatusBar(self.statusbar)

        self.retranslateUi(RecPage)
        QtCore.QMetaObject.connectSlotsByName(RecPage)

    def retranslateUi(self, RecPage):
        _translate = QtCore.QCoreApplication.translate
        RecPage.setWindowTitle(_translate("RecPage", "MainWindow"))
        self.RecBackBtn.setText(_translate("RecPage", "<"))
        self.GenerateBtn.setText(_translate("RecPage", "Generate "))
        self.label_2.setText(_translate("RecPage", "My Top 5 Song of the day"))
        self.label_3.setText(_translate("RecPage", "Top Songs On Spotify"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RecPage = QtWidgets.QMainWindow()
    ui = Ui_RecPage()
    ui.setupUi(RecPage)
    RecPage.show()
    sys.exit(app.exec_())
