# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SignUpPAge.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SignUpPage(object):
    def setupUi(self, SignUpPage):
        SignUpPage.setObjectName("SignUpPage")
        SignUpPage.resize(1920, 1080)
        SignUpPage.setMinimumSize(QtCore.QSize(1920, 1080))
        SignUpPage.setMaximumSize(QtCore.QSize(1920, 1080))
        self.centralwidget = QtWidgets.QWidget(SignUpPage)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1920, 1080))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(1920, 1080))
        self.label.setMaximumSize(QtCore.QSize(1920, 1080))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("LogInPic.png"))
        self.label.setObjectName("label")
        self.LogInLabel = QtWidgets.QLabel(self.centralwidget)
        self.LogInLabel.setGeometry(QtCore.QRect(500, 230, 911, 591))
        self.LogInLabel.setStyleSheet("background-color: rgb(90, 24, 154);\n"
"border-radius: 30px;")
        self.LogInLabel.setText("")
        self.LogInLabel.setObjectName("LogInLabel")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(870, 230, 191, 71))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic")
        font.setPointSize(26)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(223, 126, 255);")
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(540, 290, 531, 71))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic")
        font.setPointSize(26)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(223, 126, 255);")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(540, 380, 481, 71))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic")
        font.setPointSize(26)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(223, 126, 255);")
        self.label_6.setObjectName("label_6")
        self.NewUsernameInput = QtWidgets.QLineEdit(self.centralwidget)
        self.NewUsernameInput.setGeometry(QtCore.QRect(540, 350, 821, 31))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(10)
        self.NewUsernameInput.setFont(font)
        self.NewUsernameInput.setStyleSheet("background-color: rgb(171, 119, 231);\n"
"border-radius: 15px;")
        self.NewUsernameInput.setText("")
        self.NewUsernameInput.setObjectName("NewUsernameInput")
        self.NewPasswordInput = QtWidgets.QLineEdit(self.centralwidget)
        self.NewPasswordInput.setGeometry(QtCore.QRect(540, 440, 821, 31))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(10)
        self.NewPasswordInput.setFont(font)
        self.NewPasswordInput.setStyleSheet("background-color: rgb(171, 119, 231);\n"
"border-radius: 15px;")
        self.NewPasswordInput.setText("")
        self.NewPasswordInput.setObjectName("NewPasswordInput")
        self.SignUpBtn = QtWidgets.QPushButton(self.centralwidget)
        self.SignUpBtn.setGeometry(QtCore.QRect(810, 720, 291, 81))
        self.SignUpBtn.setStyleSheet("QPushButton {\n"
"    font: 20pt \"Arial Rounded MT Bold\";\n"
"    font: 75 10pt \"Georgia\";\n"
"    background-color: rgb(171, 119, 231);\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 40px;\n"
"    \n"
"}\n"
"\n"
"\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(131, 79, 191);\n"
"}\n"
"\n"
"\n"
"")
        self.SignUpBtn.setObjectName("SignUpBtn")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(690, 620, 801, 31))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(223, 126, 255);")
        self.label_7.setObjectName("label_7")
        self.AgreementCheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.AgreementCheckBox.setGeometry(QtCore.QRect(1070, 620, 101, 31))
        self.AgreementCheckBox.setStyleSheet("color: rgb(223, 126, 255);\n"
"font: 8pt \"MS Shell Dlg 2\";")
        self.AgreementCheckBox.setText("")
        self.AgreementCheckBox.setObjectName("AgreementCheckBox")
        self.ErrorLabel = QtWidgets.QLabel(self.centralwidget)
        self.ErrorLabel.setGeometry(QtCore.QRect(580, 680, 801, 31))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic")
        font.setPointSize(12)
        self.ErrorLabel.setFont(font)
        self.ErrorLabel.setStyleSheet("color: rgb(170, 0, 0);")
        self.ErrorLabel.setText("")
        self.ErrorLabel.setObjectName("ErrorLabel")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(760, 840, 801, 31))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic")
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(223, 126, 255);")
        self.label_8.setObjectName("label_8")
        self.LogInbtn = QtWidgets.QPushButton(self.centralwidget)
        self.LogInbtn.setGeometry(QtCore.QRect(1000, 840, 141, 31))
        self.LogInbtn.setStyleSheet("QPushButton {\n"
"    font: 20pt \"Arial Rounded MT Bold\";\n"
"    font: 75 10pt \"Georgia\";\n"
"    background-color: rgb(171, 119, 231);\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    \n"
"}\n"
"\n"
"\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(131, 79, 191);\n"
"}\n"
"\n"
"\n"
"")
        self.LogInbtn.setObjectName("LogInbtn")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(540, 470, 481, 71))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic")
        font.setPointSize(26)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: rgb(223, 126, 255);")
        self.label_9.setObjectName("label_9")
        self.RetypePasswordInput = QtWidgets.QLineEdit(self.centralwidget)
        self.RetypePasswordInput.setGeometry(QtCore.QRect(540, 530, 821, 31))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(10)
        self.RetypePasswordInput.setFont(font)
        self.RetypePasswordInput.setStyleSheet("background-color: rgb(171, 119, 231);\n"
"border-radius: 15px;")
        self.RetypePasswordInput.setText("")
        self.RetypePasswordInput.setObjectName("RetypePasswordInput")
        self.SignUpErrorLabel = QtWidgets.QLabel(self.centralwidget)
        self.SignUpErrorLabel.setGeometry(QtCore.QRect(550, 570, 221, 41))
        self.SignUpErrorLabel.setText("")
        self.SignUpErrorLabel.setObjectName("SignUpErrorLabel")
        self.label.raise_()
        self.LogInLabel.raise_()
        self.NewUsernameInput.raise_()
        self.NewPasswordInput.raise_()
        self.label_3.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.SignUpBtn.raise_()
        self.label_7.raise_()
        self.AgreementCheckBox.raise_()
        self.ErrorLabel.raise_()
        self.label_8.raise_()
        self.LogInbtn.raise_()
        self.label_9.raise_()
        self.RetypePasswordInput.raise_()
        self.SignUpErrorLabel.raise_()
        SignUpPage.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(SignUpPage)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1920, 26))
        self.menubar.setObjectName("menubar")
        SignUpPage.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(SignUpPage)
        self.statusbar.setObjectName("statusbar")
        SignUpPage.setStatusBar(self.statusbar)

        self.retranslateUi(SignUpPage)
        QtCore.QMetaObject.connectSlotsByName(SignUpPage)

    def retranslateUi(self, SignUpPage):
        _translate = QtCore.QCoreApplication.translate
        SignUpPage.setWindowTitle(_translate("SignUpPage", "MainWindow"))
        self.label_3.setText(_translate("SignUpPage", "Sign Up "))
        self.label_5.setText(_translate("SignUpPage", "Choose your Username"))
        self.label_6.setText(_translate("SignUpPage", "Choose your password"))
        self.SignUpBtn.setText(_translate("SignUpPage", "Sign Up"))
        self.label_7.setText(_translate("SignUpPage", "Do you agree to the terms and policies?"))
        self.label_8.setText(_translate("SignUpPage", "Already have an account?"))
        self.LogInbtn.setText(_translate("SignUpPage", "Log In"))
        self.label_9.setText(_translate("SignUpPage", "Retype the password"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SignUpPage = QtWidgets.QMainWindow()
    ui = Ui_SignUpPage()
    ui.setupUi(SignUpPage)
    SignUpPage.show()
    sys.exit(app.exec_())
