# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TheBillPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TheBillPage(object):
    def setupUi(self, TheBillPage):
        TheBillPage.setObjectName("TheBillPage")
        TheBillPage.resize(1920, 1080)
        TheBillPage.setMinimumSize(QtCore.QSize(1920, 1080))
        TheBillPage.setMaximumSize(QtCore.QSize(1920, 1080))
        self.centralwidget = QtWidgets.QWidget(TheBillPage)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, -30, 1920, 1080))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(1920, 1080))
        self.label.setMaximumSize(QtCore.QSize(1920, 1080))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("TheBillPage.png"))
        self.label.setObjectName("label")
        self.TheBillBackBtn = QtWidgets.QPushButton(self.centralwidget)
        self.TheBillBackBtn.setGeometry(QtCore.QRect(1740, 930, 151, 71))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.TheBillBackBtn.setFont(font)
        self.TheBillBackBtn.setStyleSheet("\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"\n"
"")
        self.TheBillBackBtn.setObjectName("TheBillBackBtn")
        self.ThanksLabel = QtWidgets.QLabel(self.centralwidget)
        self.ThanksLabel.setGeometry(QtCore.QRect(710, 830, 511, 51))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.ThanksLabel.setFont(font)
        self.ThanksLabel.setStyleSheet("QLabel {\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.ThanksLabel.setObjectName("ThanksLabel")
        self.BillArtistLabel = QtWidgets.QLabel(self.centralwidget)
        self.BillArtistLabel.setGeometry(QtCore.QRect(400, 300, 511, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.BillArtistLabel.setFont(font)
        self.BillArtistLabel.setStyleSheet("QLabel {\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.BillArtistLabel.setObjectName("BillArtistLabel")
        self.BillDateLabel = QtWidgets.QLabel(self.centralwidget)
        self.BillDateLabel.setGeometry(QtCore.QRect(600, 410, 511, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.BillDateLabel.setFont(font)
        self.BillDateLabel.setStyleSheet("QLabel {\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.BillDateLabel.setObjectName("BillDateLabel")
        self.BillRowLabel = QtWidgets.QLabel(self.centralwidget)
        self.BillRowLabel.setGeometry(QtCore.QRect(360, 510, 511, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.BillRowLabel.setFont(font)
        self.BillRowLabel.setStyleSheet("QLabel {\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.BillRowLabel.setObjectName("BillRowLabel")
        self.BillSeatLabel = QtWidgets.QLabel(self.centralwidget)
        self.BillSeatLabel.setGeometry(QtCore.QRect(360, 620, 511, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.BillSeatLabel.setFont(font)
        self.BillSeatLabel.setStyleSheet("QLabel {\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.BillSeatLabel.setObjectName("BillSeatLabel")
        self.BillTotalLabel = QtWidgets.QLabel(self.centralwidget)
        self.BillTotalLabel.setGeometry(QtCore.QRect(360, 730, 511, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.BillTotalLabel.setFont(font)
        self.BillTotalLabel.setStyleSheet("QLabel {\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.BillTotalLabel.setObjectName("BillTotalLabel")
        TheBillPage.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(TheBillPage)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1920, 26))
        self.menubar.setObjectName("menubar")
        TheBillPage.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(TheBillPage)
        self.statusbar.setObjectName("statusbar")
        TheBillPage.setStatusBar(self.statusbar)

        self.retranslateUi(TheBillPage)
        QtCore.QMetaObject.connectSlotsByName(TheBillPage)

    def retranslateUi(self, TheBillPage):
        _translate = QtCore.QCoreApplication.translate
        TheBillPage.setWindowTitle(_translate("TheBillPage", "MainWindow"))
        self.TheBillBackBtn.setText(_translate("TheBillPage", "<"))
        self.ThanksLabel.setText(_translate("TheBillPage", "Thank you for  Your Purchase"))
        self.BillArtistLabel.setText(_translate("TheBillPage", "ArtistName"))
        self.BillDateLabel.setText(_translate("TheBillPage", "CityNDate"))
        self.BillRowLabel.setText(_translate("TheBillPage", "Row"))
        self.BillSeatLabel.setText(_translate("TheBillPage", "Seat"))
        self.BillTotalLabel.setText(_translate("TheBillPage", "Total $"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TheBillPage = QtWidgets.QMainWindow()
    ui = Ui_TheBillPage()
    ui.setupUi(TheBillPage)
    TheBillPage.show()
    sys.exit(app.exec_())
