# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WeekendPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WeekendPage(object):
    def setupUi(self, WeekendPage):
        WeekendPage.setObjectName("WeekendPage")
        WeekendPage.resize(1920, 1080)
        WeekendPage.setMinimumSize(QtCore.QSize(1920, 1080))
        WeekendPage.setMaximumSize(QtCore.QSize(1920, 1080))
        self.centralwidget = QtWidgets.QWidget(WeekendPage)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, -50, 1920, 1080))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(1920, 1080))
        self.label.setMaximumSize(QtCore.QSize(1920, 1080))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("weekendPage.png"))
        self.label.setObjectName("label")
        self.WeekendBackBtn = QtWidgets.QPushButton(self.centralwidget)
        self.WeekendBackBtn.setGeometry(QtCore.QRect(1750, 940, 151, 71))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.WeekendBackBtn.setFont(font)
        self.WeekendBackBtn.setStyleSheet("\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"\n"
"")
        self.WeekendBackBtn.setObjectName("WeekendBackBtn")
        self.DateWeekendComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.DateWeekendComboBox.setGeometry(QtCore.QRect(330, 560, 191, 41))
        self.DateWeekendComboBox.setStyleSheet("\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"\n"
"")
        self.DateWeekendComboBox.setObjectName("DateWeekendComboBox")
        self.DateWeekendComboBox.addItem("")
        self.DateWeekendComboBox.addItem("")
        self.DateWeekendComboBox.addItem("")
        self.DateWeekendComboBox.addItem("")
        self.DateWeekendComboBox.addItem("")
        self.DateWeekendComboBox.addItem("")
        self.DateWeekendComboBox.addItem("")
        self.DateWeekendComboBox.addItem("")
        self.DateWeekendComboBox.addItem("")
        self.DateWeekendComboBox.addItem("")
        self.DateWeekendComboBox.addItem("")
        self.DateWeekendComboBox.addItem("")
        self.DateWeekendComboBox.addItem("")
        self.DateWeekendComboBox.addItem("")
        self.DateWeekendComboBox.addItem("")
        self.DateWeekendComboBox.addItem("")
        self.DateWeekendComboBox.addItem("")
        self.DateWeekendComboBox.addItem("")
        self.DateWeekendComboBox.addItem("")
        self.DateWeekendComboBox.addItem("")
        self.DateWeekendComboBox.addItem("")
        self.DateWeekendComboBox.addItem("")
        self.DateWeekendComboBox.addItem("")
        self.WeekendPriceLabel = QtWidgets.QLabel(self.centralwidget)
        self.WeekendPriceLabel.setGeometry(QtCore.QRect(70, 490, 451, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.WeekendPriceLabel.setFont(font)
        self.WeekendPriceLabel.setStyleSheet("QLabel {\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.WeekendPriceLabel.setObjectName("WeekendPriceLabel")
        self.DateWeekendLabel = QtWidgets.QLabel(self.centralwidget)
        self.DateWeekendLabel.setGeometry(QtCore.QRect(70, 560, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.DateWeekendLabel.setFont(font)
        self.DateWeekendLabel.setStyleSheet("QLabel {\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.DateWeekendLabel.setObjectName("DateWeekendLabel")
        self.QuantityWeekendLabel = QtWidgets.QLabel(self.centralwidget)
        self.QuantityWeekendLabel.setGeometry(QtCore.QRect(70, 620, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.QuantityWeekendLabel.setFont(font)
        self.QuantityWeekendLabel.setStyleSheet("QLabel {\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.QuantityWeekendLabel.setObjectName("QuantityWeekendLabel")
        self.ConfirmWeekendBtn = QtWidgets.QPushButton(self.centralwidget)
        self.ConfirmWeekendBtn.setGeometry(QtCore.QRect(250, 850, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ConfirmWeekendBtn.setFont(font)
        self.ConfirmWeekendBtn.setStyleSheet("\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"\n"
"")
        self.ConfirmWeekendBtn.setObjectName("ConfirmWeekendBtn")
        self.RowWeekendLabel = QtWidgets.QLabel(self.centralwidget)
        self.RowWeekendLabel.setGeometry(QtCore.QRect(70, 680, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.RowWeekendLabel.setFont(font)
        self.RowWeekendLabel.setStyleSheet("QLabel {\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.RowWeekendLabel.setObjectName("RowWeekendLabel")
        self.SeatWeekendLabel = QtWidgets.QLabel(self.centralwidget)
        self.SeatWeekendLabel.setGeometry(QtCore.QRect(70, 740, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.SeatWeekendLabel.setFont(font)
        self.SeatWeekendLabel.setStyleSheet("QLabel {\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.SeatWeekendLabel.setObjectName("SeatWeekendLabel")
        self.RowWeekendComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.RowWeekendComboBox.setGeometry(QtCore.QRect(330, 680, 191, 41))
        self.RowWeekendComboBox.setStyleSheet("\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"\n"
"")
        self.RowWeekendComboBox.setObjectName("RowWeekendComboBox")
        self.RowWeekendComboBox.addItem("")
        self.RowWeekendComboBox.addItem("")
        self.RowWeekendComboBox.addItem("")
        self.RowWeekendComboBox.addItem("")
        self.RowWeekendComboBox.addItem("")
        self.RowWeekendComboBox.addItem("")
        self.RowWeekendComboBox.addItem("")
        self.RowWeekendComboBox.addItem("")
        self.RowWeekendComboBox.addItem("")
        self.RowWeekendComboBox.addItem("")
        self.RowWeekendComboBox.addItem("")
        self.RowWeekendComboBox.addItem("")
        self.RowWeekendComboBox.addItem("")
        self.RowWeekendComboBox.addItem("")
        self.RowWeekendComboBox.addItem("")
        self.RowWeekendComboBox.addItem("")
        self.RowWeekendComboBox.addItem("")
        self.RowWeekendComboBox.addItem("")
        self.RowWeekendComboBox.addItem("")
        self.RowWeekendComboBox.addItem("")
        self.RowWeekendComboBox.addItem("")
        self.RowWeekendComboBox.addItem("")
        self.RowWeekendComboBox.addItem("")
        self.RowWeekendComboBox.addItem("")
        self.RowWeekendComboBox.addItem("")
        self.RowWeekendComboBox.addItem("")
        self.RowWeekendComboBox.addItem("")
        self.RowWeekendComboBox.addItem("")
        self.RowWeekendComboBox.addItem("")
        self.RowWeekendComboBox.addItem("")
        self.SeatWeekendComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.SeatWeekendComboBox.setGeometry(QtCore.QRect(330, 740, 191, 41))
        self.SeatWeekendComboBox.setStyleSheet("\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"\n"
"")
        self.SeatWeekendComboBox.setObjectName("SeatWeekendComboBox")
        self.SeatWeekendComboBox.addItem("")
        self.SeatWeekendComboBox.addItem("")
        self.SeatWeekendComboBox.addItem("")
        self.SeatWeekendComboBox.addItem("")
        self.SeatWeekendComboBox.addItem("")
        self.SeatWeekendComboBox.addItem("")
        self.SeatWeekendComboBox.addItem("")
        self.SeatWeekendComboBox.addItem("")
        self.SeatWeekendComboBox.addItem("")
        self.SeatWeekendComboBox.addItem("")
        self.SeatWeekendComboBox.addItem("")
        self.SeatWeekendComboBox.addItem("")
        self.SeatWeekendComboBox.addItem("")
        self.SeatWeekendComboBox.addItem("")
        self.SeatWeekendComboBox.addItem("")
        self.SeatWeekendComboBox.addItem("")
        self.SeatWeekendComboBox.addItem("")
        self.SeatWeekendComboBox.addItem("")
        self.SeatWeekendComboBox.addItem("")
        self.SeatWeekendComboBox.addItem("")
        self.SeatWeekendComboBox.addItem("")
        self.SeatWeekendComboBox.addItem("")
        self.SeatWeekendComboBox.addItem("")
        self.SeatWeekendComboBox.addItem("")
        self.SeatWeekendComboBox.addItem("")
        self.SeatWeekendComboBox.addItem("")
        self.SeatWeekendComboBox.addItem("")
        self.SeatWeekendComboBox.addItem("")
        self.SeatWeekendComboBox.addItem("")
        self.SeatWeekendComboBox.addItem("")
        self.TotalWeekendLabel = QtWidgets.QLabel(self.centralwidget)
        self.TotalWeekendLabel.setGeometry(QtCore.QRect(70, 800, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.TotalWeekendLabel.setFont(font)
        self.TotalWeekendLabel.setStyleSheet("QLabel {\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.TotalWeekendLabel.setObjectName("TotalWeekendLabel")
        self.TotalWeekendLabelValue = QtWidgets.QLabel(self.centralwidget)
        self.TotalWeekendLabelValue.setGeometry(QtCore.QRect(330, 800, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.TotalWeekendLabelValue.setFont(font)
        self.TotalWeekendLabelValue.setStyleSheet("QLabel {\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.TotalWeekendLabelValue.setObjectName("TotalWeekendLabelValue")
        self.PayWeekendBtn = QtWidgets.QPushButton(self.centralwidget)
        self.PayWeekendBtn.setEnabled(False)
        self.PayWeekendBtn.setGeometry(QtCore.QRect(430, 930, 271, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.PayWeekendBtn.setFont(font)
        self.PayWeekendBtn.setStyleSheet("\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"\n"
"")
        self.PayWeekendBtn.setObjectName("PayWeekendBtn")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(330, 620, 191, 41))
        self.lineEdit.setStyleSheet("\n"
"    background-color: #5A189A;\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 6px 12px;\n"
"    font-weight: bold;\n"
"")
        self.lineEdit.setObjectName("lineEdit")
        WeekendPage.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(WeekendPage)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1920, 26))
        self.menubar.setObjectName("menubar")
        WeekendPage.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(WeekendPage)
        self.statusbar.setObjectName("statusbar")
        WeekendPage.setStatusBar(self.statusbar)

        self.retranslateUi(WeekendPage)
        QtCore.QMetaObject.connectSlotsByName(WeekendPage)

    def retranslateUi(self, WeekendPage):
        _translate = QtCore.QCoreApplication.translate
        WeekendPage.setWindowTitle(_translate("WeekendPage", "MainWindow"))
        self.WeekendBackBtn.setText(_translate("WeekendPage", "<"))
        self.DateWeekendComboBox.setItemText(0, _translate("WeekendPage", "5 July – Las Vegas, NV @ Allegiant Stadium "))
        self.DateWeekendComboBox.setItemText(1, _translate("WeekendPage", "8 July -  Santa Clara, CA @ Levi’s Stadium"))
        self.DateWeekendComboBox.setItemText(2, _translate("WeekendPage", "9 July -Santa Clara, CA @ Levi’s Stadium"))
        self.DateWeekendComboBox.setItemText(3, _translate("WeekendPage", "12 July -Seattle, WA @ Lumen Field "))
        self.DateWeekendComboBox.setItemText(4, _translate("WeekendPage", "15 July -Vancouver, BC @ BC Place"))
        self.DateWeekendComboBox.setItemText(5, _translate("WeekendPage", "16 July - Vancouver, BC @ BC Place"))
        self.DateWeekendComboBox.setItemText(6, _translate("WeekendPage", "19 July -  Edmonton, AB @ Commonwealth Stadium"))
        self.DateWeekendComboBox.setItemText(7, _translate("WeekendPage", "24 July -Montreal, QC @ Parc Jean‑Drapeau"))
        self.DateWeekendComboBox.setItemText(8, _translate("WeekendPage", "25 July -Montreal, QC @ Parc Jean‑Drapeau"))
        self.DateWeekendComboBox.setItemText(9, _translate("WeekendPage", "27 July - Toronto, ON @ Rogers Centre"))
        self.DateWeekendComboBox.setItemText(10, _translate("WeekendPage", "28 July - Toronto, ON @ Rogers Centre"))
        self.DateWeekendComboBox.setItemText(11, _translate("WeekendPage", "30 July -Philadelphia, PA @ Lincoln Financial Field"))
        self.DateWeekendComboBox.setItemText(12, _translate("WeekendPage", "31 July -Philadelphia, PA @ Lincoln Financial Field"))
        self.DateWeekendComboBox.setItemText(13, _translate("WeekendPage", "2 August - Landover, MD @ Northwest Stadium"))
        self.DateWeekendComboBox.setItemText(14, _translate("WeekendPage", "12 August -Nashville, TN @ Nissan Stadium"))
        self.DateWeekendComboBox.setItemText(15, _translate("WeekendPage", "15 August -Miami Gardens, FL @ Hard Rock Stadium "))
        self.DateWeekendComboBox.setItemText(16, _translate("WeekendPage", "21 August -Atlanta, GA @ Mercedes‑Benz Stadium"))
        self.DateWeekendComboBox.setItemText(17, _translate("WeekendPage", "24 August -Orlando, FL @ Camping World Stadium"))
        self.DateWeekendComboBox.setItemText(18, _translate("WeekendPage", "27 August -Arlington, TX @ AT&T Stadium"))
        self.DateWeekendComboBox.setItemText(19, _translate("WeekendPage", "28 August -Arlington, TX @ AT&T Stadium"))
        self.DateWeekendComboBox.setItemText(20, _translate("WeekendPage", "30 August - Houston, TX @ NRG Stadium"))
        self.DateWeekendComboBox.setItemText(21, _translate("WeekendPage", "31 August - Houston, TX @ NRG Stadium"))
        self.DateWeekendComboBox.setItemText(22, _translate("WeekendPage", "3 September -  San Antonio, TX @ Alamodome"))
        self.WeekendPriceLabel.setText(_translate("WeekendPage", "Price : 450$"))
        self.DateWeekendLabel.setText(_translate("WeekendPage", "Date & City"))
        self.QuantityWeekendLabel.setText(_translate("WeekendPage", "Quantity"))
        self.ConfirmWeekendBtn.setText(_translate("WeekendPage", "Confirm "))
        self.RowWeekendLabel.setText(_translate("WeekendPage", "The Row"))
        self.SeatWeekendLabel.setText(_translate("WeekendPage", "The seat"))
        self.RowWeekendComboBox.setItemText(0, _translate("WeekendPage", "1"))
        self.RowWeekendComboBox.setItemText(1, _translate("WeekendPage", "2"))
        self.RowWeekendComboBox.setItemText(2, _translate("WeekendPage", "3"))
        self.RowWeekendComboBox.setItemText(3, _translate("WeekendPage", "4"))
        self.RowWeekendComboBox.setItemText(4, _translate("WeekendPage", "5"))
        self.RowWeekendComboBox.setItemText(5, _translate("WeekendPage", "6"))
        self.RowWeekendComboBox.setItemText(6, _translate("WeekendPage", "7"))
        self.RowWeekendComboBox.setItemText(7, _translate("WeekendPage", "8"))
        self.RowWeekendComboBox.setItemText(8, _translate("WeekendPage", "9"))
        self.RowWeekendComboBox.setItemText(9, _translate("WeekendPage", "10"))
        self.RowWeekendComboBox.setItemText(10, _translate("WeekendPage", "11"))
        self.RowWeekendComboBox.setItemText(11, _translate("WeekendPage", "12"))
        self.RowWeekendComboBox.setItemText(12, _translate("WeekendPage", "13"))
        self.RowWeekendComboBox.setItemText(13, _translate("WeekendPage", "14"))
        self.RowWeekendComboBox.setItemText(14, _translate("WeekendPage", "15"))
        self.RowWeekendComboBox.setItemText(15, _translate("WeekendPage", "16"))
        self.RowWeekendComboBox.setItemText(16, _translate("WeekendPage", "17"))
        self.RowWeekendComboBox.setItemText(17, _translate("WeekendPage", "18"))
        self.RowWeekendComboBox.setItemText(18, _translate("WeekendPage", "19"))
        self.RowWeekendComboBox.setItemText(19, _translate("WeekendPage", "20"))
        self.RowWeekendComboBox.setItemText(20, _translate("WeekendPage", "21"))
        self.RowWeekendComboBox.setItemText(21, _translate("WeekendPage", "22"))
        self.RowWeekendComboBox.setItemText(22, _translate("WeekendPage", "23"))
        self.RowWeekendComboBox.setItemText(23, _translate("WeekendPage", "24"))
        self.RowWeekendComboBox.setItemText(24, _translate("WeekendPage", "25"))
        self.RowWeekendComboBox.setItemText(25, _translate("WeekendPage", "26"))
        self.RowWeekendComboBox.setItemText(26, _translate("WeekendPage", "27"))
        self.RowWeekendComboBox.setItemText(27, _translate("WeekendPage", "28"))
        self.RowWeekendComboBox.setItemText(28, _translate("WeekendPage", "29"))
        self.RowWeekendComboBox.setItemText(29, _translate("WeekendPage", "30"))
        self.SeatWeekendComboBox.setItemText(0, _translate("WeekendPage", "1"))
        self.SeatWeekendComboBox.setItemText(1, _translate("WeekendPage", "2"))
        self.SeatWeekendComboBox.setItemText(2, _translate("WeekendPage", "3"))
        self.SeatWeekendComboBox.setItemText(3, _translate("WeekendPage", "4"))
        self.SeatWeekendComboBox.setItemText(4, _translate("WeekendPage", "5"))
        self.SeatWeekendComboBox.setItemText(5, _translate("WeekendPage", "6"))
        self.SeatWeekendComboBox.setItemText(6, _translate("WeekendPage", "7"))
        self.SeatWeekendComboBox.setItemText(7, _translate("WeekendPage", "8"))
        self.SeatWeekendComboBox.setItemText(8, _translate("WeekendPage", "9"))
        self.SeatWeekendComboBox.setItemText(9, _translate("WeekendPage", "10"))
        self.SeatWeekendComboBox.setItemText(10, _translate("WeekendPage", "11"))
        self.SeatWeekendComboBox.setItemText(11, _translate("WeekendPage", "12"))
        self.SeatWeekendComboBox.setItemText(12, _translate("WeekendPage", "13"))
        self.SeatWeekendComboBox.setItemText(13, _translate("WeekendPage", "14"))
        self.SeatWeekendComboBox.setItemText(14, _translate("WeekendPage", "15"))
        self.SeatWeekendComboBox.setItemText(15, _translate("WeekendPage", "16"))
        self.SeatWeekendComboBox.setItemText(16, _translate("WeekendPage", "17"))
        self.SeatWeekendComboBox.setItemText(17, _translate("WeekendPage", "18"))
        self.SeatWeekendComboBox.setItemText(18, _translate("WeekendPage", "19"))
        self.SeatWeekendComboBox.setItemText(19, _translate("WeekendPage", "20"))
        self.SeatWeekendComboBox.setItemText(20, _translate("WeekendPage", "21"))
        self.SeatWeekendComboBox.setItemText(21, _translate("WeekendPage", "22"))
        self.SeatWeekendComboBox.setItemText(22, _translate("WeekendPage", "23"))
        self.SeatWeekendComboBox.setItemText(23, _translate("WeekendPage", "24"))
        self.SeatWeekendComboBox.setItemText(24, _translate("WeekendPage", "25"))
        self.SeatWeekendComboBox.setItemText(25, _translate("WeekendPage", "26"))
        self.SeatWeekendComboBox.setItemText(26, _translate("WeekendPage", "27"))
        self.SeatWeekendComboBox.setItemText(27, _translate("WeekendPage", "28"))
        self.SeatWeekendComboBox.setItemText(28, _translate("WeekendPage", "29"))
        self.SeatWeekendComboBox.setItemText(29, _translate("WeekendPage", "30"))
        self.TotalWeekendLabel.setText(_translate("WeekendPage", "In Total"))
        self.TotalWeekendLabelValue.setText(_translate("WeekendPage", "0$"))
        self.PayWeekendBtn.setText(_translate("WeekendPage", "Choose The Quantity First"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WeekendPage = QtWidgets.QMainWindow()
    ui = Ui_WeekendPage()
    ui.setupUi(WeekendPage)
    WeekendPage.show()
    sys.exit(app.exec_())
